# Generated by Django 5.0.14 on 2026-03-20 19:09

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                ("description", encrypted_model_fields.fields.EncryptedTextField()),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Detected language code (fr, en, es, etc.) from dream title/description",
                        max_length=10,
                    ),
                ),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="AI-generated analysis and insights",
                        null=True,
                    ),
                ),
                ("vision_image_url", models.URLField(blank=True, max_length=500)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Hex color for calendar display (e.g. #8B5CF6). Auto-assigned if blank.",
                        max_length=7,
                    ),
                ),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this dream is publicly visible to other users",
                    ),
                ),
                (
                    "is_favorited",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has favorited this dream on the vision board",
                    ),
                ),
                ("has_two_minute_start", models.BooleanField(default=False)),
                (
                    "calibration_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Status of the calibration questionnaire",
                        max_length=20,
                    ),
                ),
                (
                    "plan_phase",
                    models.CharField(
                        choices=[
                            ("none", "No Plan"),
                            ("skeleton", "Skeleton Only"),
                            ("partial", "Partial Tasks"),
                            ("full", "Full Plan"),
                        ],
                        db_index=True,
                        default="none",
                        max_length=20,
                    ),
                ),
                ("plan_skeleton", models.JSONField(blank=True, null=True)),
                ("tasks_generated_through_month", models.IntegerField(default=0)),
                ("last_checkin_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_checkin_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("checkin_count", models.IntegerField(default=0)),
                (
                    "checkin_interval_days",
                    models.IntegerField(
                        default=14,
                        help_text="Days between check-ins (7 if behind, 14 normal, 21 if ahead)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dreams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("collaborator", "Collaborator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_collaborators",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "content",
                    models.TextField(
                        help_text="Journal entry content stored as HTML or markdown"
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("excited", "Excited"),
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("frustrated", "Frustrated"),
                            ("motivated", "Motivated"),
                            ("reflective", "Reflective"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dream_journal_entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DreamTagging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_taggings",
            },
        ),
        migrations.CreateModel(
            name="DreamTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Fitness"),
                            ("career", "Career & Business"),
                            ("education", "Education & Learning"),
                            ("finance", "Finance & Savings"),
                            ("creative", "Creative & Arts"),
                            ("personal", "Personal Growth"),
                            ("hobbies", "Hobbies & Skills"),
                            ("social", "Social & Relationships"),
                            ("relationships", "Relationships"),
                            ("travel", "Travel & Adventure"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "template_goals",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of goal templates: [{title, description, order, tasks: [{title, description, order, duration_mins}]}]",
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.IntegerField(
                        default=90,
                        help_text="Estimated number of days to complete this dream.",
                    ),
                ),
                (
                    "suggested_timeline",
                    models.CharField(
                        blank=True,
                        help_text='Human-readable timeline, e.g. "3 months", "1 year"',
                        max_length=50,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#8B5CF6",
                        help_text="Accent color for template card display",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dream_templates",
                "ordering": ["-is_featured", "-usage_count"],
            },
        ),
        migrations.CreateModel(
            name="ProgressPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="progress_photos/")),
                (
                    "caption",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "ai_analysis",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(help_text="When the progress photo was taken"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "progress_photos",
                "ordering": ["-taken_at"],
            },
        ),
        migrations.CreateModel(
            name="SharedDream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("view", "View Only"), ("comment", "Can Comment")],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "shared_dreams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisionBoardImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.URLField(blank=True, max_length=500)),
                (
                    "image_file",
                    models.ImageField(blank=True, upload_to="vision_boards/"),
                ),
                ("caption", models.CharField(blank=True, max_length=500)),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "vision_board_images",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
