# Generated by Django 5.0.1 on 2026-02-05 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalibrationResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="AI-generated calibration question"),
                ),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="User response to the question"
                    ),
                ),
                (
                    "question_number",
                    models.IntegerField(
                        help_text="Order of question in the calibration flow"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Question category: experience, timeline, resources, motivation, constraints, specifics, lifestyle, preferences",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "calibration_responses",
                "ordering": ["dream", "question_number"],
            },
        ),
        migrations.CreateModel(
            name="Dream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=50),
                ),
                ("target_date", models.DateTimeField(blank=True, null=True)),
                ("priority", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "ai_analysis",
                    models.JSONField(
                        blank=True,
                        help_text="AI-generated analysis and insights",
                        null=True,
                    ),
                ),
                ("vision_image_url", models.URLField(blank=True, max_length=500)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("has_two_minute_start", models.BooleanField(default=False)),
                (
                    "calibration_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        help_text="Status of the calibration questionnaire",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dreams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField()),
                ("estimated_minutes", models.IntegerField(blank=True, null=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_enabled", models.BooleanField(default=True)),
                ("reminder_time", models.DateTimeField(blank=True, null=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "goals",
                "ordering": ["dream", "order"],
            },
        ),
        migrations.CreateModel(
            name="Obstacle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "obstacle_type",
                    models.CharField(
                        choices=[("predicted", "Predicted"), ("actual", "Actual")],
                        default="predicted",
                        max_length=20,
                    ),
                ),
                ("solution", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "obstacles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField()),
                (
                    "scheduled_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "scheduled_time",
                    models.CharField(
                        blank=True, help_text="HH:MM format", max_length=5
                    ),
                ),
                ("duration_mins", models.IntegerField(blank=True, null=True)),
                (
                    "recurrence",
                    models.JSONField(
                        blank=True,
                        help_text='Recurrence pattern: {type: "daily|weekly|monthly", interval: 1, ...}',
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_two_minute_start", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["goal", "scheduled_date", "order"],
            },
        ),
    ]
