# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dreams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreamcollaborator",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborators",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="dreamcollaborator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dream_collaborations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreamjournal",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_entries",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="dreamtagging",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taggings",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="dreamtagging",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taggings",
                to="dreams.dreamtag",
            ),
        ),
        migrations.AddIndex(
            model_name="dreamtemplate",
            index=models.Index(
                fields=["category", "is_active"], name="dream_templ_categor_25cfc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dreamtemplate",
            index=models.Index(
                fields=["is_featured", "is_active"],
                name="dream_templ_is_feat_f47c6a_idx",
            ),
        ),
        migrations.AddField(
            model_name="progressphoto",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_photos",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="shareddream",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="shareddream",
            name="shared_by",
            field=models.ForeignKey(
                help_text="The user who shared the dream.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dreams_shared",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shareddream",
            name="shared_with",
            field=models.ForeignKey(
                help_text="The user the dream was shared with.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dreams_shared_with_me",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visionboardimage",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vision_images",
                to="dreams.dream",
            ),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["user", "status"], name="dreams_user_id_f65fcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(fields=["category"], name="dreams_categor_913d7e_idx"),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["target_date"], name="dreams_target__080048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["is_public", "status"], name="dreams_is_publ_1203f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dreamcollaborator",
            index=models.Index(fields=["user", "role"], name="idx_collab_user_role"),
        ),
        migrations.AddIndex(
            model_name="dreamcollaborator",
            index=models.Index(fields=["dream", "user"], name="idx_collab_dream_user"),
        ),
        migrations.AddConstraint(
            model_name="dreamcollaborator",
            constraint=models.UniqueConstraint(
                fields=("dream", "user"), name="unique_dream_collaborator"
            ),
        ),
        migrations.AddIndex(
            model_name="dreamjournal",
            index=models.Index(
                fields=["dream", "-created_at"], name="dream_journ_dream_i_8a21de_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dreamtagging",
            constraint=models.UniqueConstraint(
                fields=("dream", "tag"), name="unique_dream_tag"
            ),
        ),
        migrations.AddIndex(
            model_name="progressphoto",
            index=models.Index(
                fields=["dream", "-taken_at"], name="progress_ph_dream_i_fd173a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="shareddream",
            index=models.Index(
                fields=["shared_with"], name="idx_shared_dream_recipient"
            ),
        ),
        migrations.AddConstraint(
            model_name="shareddream",
            constraint=models.UniqueConstraint(
                fields=("dream", "shared_with"), name="unique_shared_dream"
            ),
        ),
        migrations.AddIndex(
            model_name="visionboardimage",
            index=models.Index(
                fields=["dream", "order"], name="vision_boar_dream_i_dd0a2e_idx"
            ),
        ),
    ]
