# Generated by Django 5.0.6 on 2026-02-22 22:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0003_dreamtag_dreamtemplate_dreamcollaborator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamProgressSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('progress_percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_snapshots', to='dreams.dream')),
            ],
            options={
                'db_table': 'dream_progress_snapshots',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['dream', '-date'], name='dream_progr_dream_i_6974d7_idx')],
                'unique_together': {('dream', 'date')},
            },
        ),
        migrations.CreateModel(
            name='VisionBoardImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('image_file', models.ImageField(blank=True, upload_to='vision_boards/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_images', to='dreams.dream')),
            ],
            options={
                'db_table': 'vision_board_images',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['dream', 'order'], name='vision_boar_dream_i_dd0a2e_idx')],
            },
        ),
    ]
