# Generated by Django 5.2.6 on 2026-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0004_dreamprogresssnapshot_visionboardimage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "-created_at"], name="tasks_status_ec5702_idx"
            ),
        ),
    ]
