# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0005_task_tasks_status_ec5702_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calibrationresponse",
            name="answer",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="User response to the question (encrypted at rest)",
            ),
        ),
        migrations.AlterField(
            model_name="dream",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="dream",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="goal",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="obstacle",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="obstacle",
            name="solution",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="obstacle",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
