# Generated by Django 5.2.6 on 2026-02-26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0006_alter_calibrationresponse_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
    ]
