# Generated by Django 5.2.11 on 2026-02-27 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0007_alter_dream_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dreamcollaborator',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dreamprogresssnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dreamtagging',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shareddream',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dreamcollaborator',
            constraint=models.UniqueConstraint(fields=('dream', 'user'), name='unique_dream_collaborator'),
        ),
        migrations.AddConstraint(
            model_name='dreamprogresssnapshot',
            constraint=models.UniqueConstraint(fields=('dream', 'date'), name='unique_dream_progress_date'),
        ),
        migrations.AddConstraint(
            model_name='dreamtagging',
            constraint=models.UniqueConstraint(fields=('dream', 'tag'), name='unique_dream_tag'),
        ),
        migrations.AddConstraint(
            model_name='shareddream',
            constraint=models.UniqueConstraint(fields=('dream', 'shared_with'), name='unique_shared_dream'),
        ),
    ]
