# Generated by Django 5.2.11 on 2026-02-27

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0008_alter_dreamcollaborator_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
