# Generated by Django 5.2.11 on 2026-02-27

import uuid
import encrypted_model_fields.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0009_make_dream_description_required"),
    ]

    operations = [
        # 1. Create the Milestone model
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField(max_length=255)),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order within the dream (1 = first milestone)"
                    ),
                ),
                (
                    "target_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date by which this milestone should be achieved",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="dreams.dream",
                    ),
                ),
            ],
            options={
                "db_table": "milestones",
                "ordering": ["dream", "order"],
                "indexes": [
                    models.Index(
                        fields=["dream", "order"],
                        name="milestones_dream_i_idx",
                    ),
                    models.Index(
                        fields=["status"],
                        name="milestones_status_idx",
                    ),
                    models.Index(
                        fields=["target_date"],
                        name="milestones_target_idx",
                    ),
                ],
            },
        ),
        # 2. Add milestone FK to Goal (nullable for backward compatibility)
        migrations.AddField(
            model_name="goal",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="The milestone this goal belongs to (null for legacy goals without milestones)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="dreams.milestone",
            ),
        ),
        # 3. Add milestone FK to Obstacle (nullable)
        migrations.AddField(
            model_name="obstacle",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="The milestone this obstacle is linked to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="dreams.milestone",
            ),
        ),
        # 4. Add goal FK to Obstacle (nullable)
        migrations.AddField(
            model_name="obstacle",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                help_text="The goal this obstacle is linked to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="dreams.goal",
            ),
        ),
        # 5. Add indexes for the new FKs
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["milestone", "order"],
                name="goals_milestone_order_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="obstacle",
            index=models.Index(
                fields=["milestone"],
                name="obstacles_milestone_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="obstacle",
            index=models.Index(
                fields=["goal"],
                name="obstacles_goal_idx",
            ),
        ),
    ]
