# Generated by Django 5.2.11 on 2026-02-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0010_milestone_goal_milestone_obstacle_milestone_goal"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Milestone",
            new_name="DreamMilestone",
        ),
    ]
