# Generated by Django 5.2.11 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0011_rename_milestone_to_dreammilestone"),
    ]

    operations = [
        # DreamMilestone: expected_date and deadline_date
        migrations.AddField(
            model_name="dreammilestone",
            name="expected_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Ideal/soft date to complete this milestone (no penalty if missed)",
            ),
        ),
        migrations.AddField(
            model_name="dreammilestone",
            name="deadline_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Hard deadline — must be done by this date",
            ),
        ),
        # Goal: expected_date and deadline_date
        migrations.AddField(
            model_name="goal",
            name="expected_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Ideal/soft date to complete this goal (no penalty if missed)",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="deadline_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Hard deadline — must be done by this date",
            ),
        ),
        # Task: expected_date and deadline_date
        migrations.AddField(
            model_name="task",
            name="expected_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Ideal/soft date to do this task (no penalty if missed)",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="deadline_date",
            field=models.DateField(
                blank=True,
                null=True,
                help_text="Hard deadline — must be done by this date",
            ),
        ),
        # Indexes for calendar queries
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(fields=["expected_date"], name="milestones_expecte_d1a2b3_idx"),
        ),
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(fields=["deadline_date"], name="milestones_deadlin_e4f5g6_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["expected_date"], name="goals_expecte_h7i8j9_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["deadline_date"], name="goals_deadlin_k0l1m2_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["expected_date"], name="tasks_expecte_n3o4p5_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["deadline_date"], name="tasks_deadlin_q6r7s8_idx"),
        ),
    ]
