# Generated by Django 5.0.14 on 2026-03-01 00:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0012_add_expected_and_deadline_dates"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goal",
            options={"ordering": ["dream", "milestone__order", "order"]},
        ),
        migrations.RenameIndex(
            model_name="dreammilestone",
            new_name="milestones_dream_i_4a2f78_idx",
            old_name="milestones_dream_i_idx",
        ),
        migrations.RenameIndex(
            model_name="dreammilestone",
            new_name="milestones_status_2abe2f_idx",
            old_name="milestones_status_idx",
        ),
        migrations.RenameIndex(
            model_name="dreammilestone",
            new_name="milestones_target__3769ed_idx",
            old_name="milestones_target_idx",
        ),
        migrations.RenameIndex(
            model_name="dreammilestone",
            new_name="milestones_expecte_47e9cb_idx",
            old_name="milestones_expecte_d1a2b3_idx",
        ),
        migrations.RenameIndex(
            model_name="dreammilestone",
            new_name="milestones_deadlin_151c63_idx",
            old_name="milestones_deadlin_e4f5g6_idx",
        ),
        migrations.RenameIndex(
            model_name="goal",
            new_name="goals_milesto_67ee09_idx",
            old_name="goals_milestone_order_idx",
        ),
        migrations.RenameIndex(
            model_name="goal",
            new_name="goals_expecte_1bcf5b_idx",
            old_name="goals_expecte_h7i8j9_idx",
        ),
        migrations.RenameIndex(
            model_name="goal",
            new_name="goals_deadlin_5df156_idx",
            old_name="goals_deadlin_k0l1m2_idx",
        ),
        migrations.RenameIndex(
            model_name="obstacle",
            new_name="obstacles_milesto_961843_idx",
            old_name="obstacles_milestone_idx",
        ),
        migrations.RenameIndex(
            model_name="obstacle",
            new_name="obstacles_goal_id_319a13_idx",
            old_name="obstacles_goal_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_expecte_e0f58c_idx",
            old_name="tasks_expecte_n3o4p5_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="tasks_deadlin_68dd57_idx",
            old_name="tasks_deadlin_q6r7s8_idx",
        ),
    ]
