# Generated by Django 5.0.14 on 2026-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0013_alter_goal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this dream is publicly visible to other users'),
        ),
    ]
