# Generated by Django 5.2.11 on 2026-03-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0015_dream_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamtemplate',
            name='color',
            field=models.CharField(default='#8B5CF6', help_text='Accent color for template card display', max_length=20),
        ),
        migrations.AddField(
            model_name='dreamtemplate',
            name='suggested_timeline',
            field=models.CharField(blank=True, help_text='Human-readable timeline, e.g. "3 months", "1 year"', max_length=50),
        ),
        migrations.AlterField(
            model_name='dreamtemplate',
            name='category',
            field=models.CharField(choices=[('health', 'Health & Fitness'), ('career', 'Career & Business'), ('education', 'Education & Learning'), ('finance', 'Finance & Savings'), ('creative', 'Creative & Arts'), ('personal', 'Personal Growth'), ('hobbies', 'Hobbies & Skills'), ('social', 'Social & Relationships'), ('relationships', 'Relationships'), ('travel', 'Travel & Adventure')], db_index=True, max_length=30),
        ),
    ]
