# Generated by Django 5.0.14 on 2026-03-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0015_dream_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Detected language code (fr, en, es, etc.) from dream title/description', max_length=10),
        ),
    ]
