# Generated by Django 5.0.14 on 2026-03-06 20:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_alter_messagereadstatus_unique_together_and_more'),
        ('dreams', '0016_persona_and_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='checkin_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dream',
            name='last_checkin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='next_checkin_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='plan_phase',
            field=models.CharField(choices=[('none', 'No Plan'), ('skeleton', 'Skeleton Only'), ('partial', 'Partial Tasks'), ('full', 'Full Plan')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='dream',
            name='plan_skeleton',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dream',
            name='tasks_generated_through_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dreammilestone',
            name='has_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PlanCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ai_processing', 'AI Processing'), ('awaiting_user', 'Awaiting User Response'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('progress_at_checkin', models.FloatField(default=0.0)),
                ('tasks_completed_since_last', models.IntegerField(default=0)),
                ('tasks_overdue_at_checkin', models.IntegerField(default=0)),
                ('ai_actions', models.JSONField(default=list)),
                ('tasks_created', models.IntegerField(default=0)),
                ('milestones_adjusted', models.IntegerField(default=0)),
                ('months_generated_through', models.IntegerField(default=0)),
                ('coaching_message', models.TextField(blank=True)),
                ('adjustment_summary', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_records', to='conversations.conversation')),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='dreams.dream')),
            ],
            options={
                'db_table': 'plan_checkins',
                'ordering': ['-scheduled_for'],
            },
        ),
    ]
