# Generated by Django 5.2.11 on 2026-03-04 05:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0016_dreamtemplate_color_dreamtemplate_suggested_timeline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamJournal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField(help_text='Journal entry content stored as HTML or markdown')),
                ('mood', models.CharField(blank=True, choices=[('excited', 'Excited'), ('happy', 'Happy'), ('neutral', 'Neutral'), ('frustrated', 'Frustrated'), ('motivated', 'Motivated'), ('reflective', 'Reflective')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='dreams.dream')),
            ],
            options={
                'db_table': 'dream_journal_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dream', '-created_at'], name='dream_journ_dream_i_8a21de_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Planned duration in minutes')),
                ('actual_minutes', models.PositiveIntegerField(default=0, help_text='Actual time focused in minutes')),
                ('session_type', models.CharField(choices=[('work', 'Work'), ('break', 'Break')], default='work', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_sessions', to='dreams.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'focus_sessions',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', '-started_at'], name='focus_sessi_user_id_ba172e_idx'), models.Index(fields=['user', 'completed'], name='focus_sessi_user_id_1027c7_idx')],
            },
        ),
    ]
