# Generated by Django 5.2.11 on 2026-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0017_add_dream_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Hex color for calendar display (e.g. #8B5CF6). Auto-assigned if blank.', max_length=7),
        ),
    ]
