# Generated by Django 5.0.14 on 2026-03-06 20:58

from django.db import migrations


def backfill_plan_phase(apps, schema_editor):
    Dream = apps.get_model('dreams', 'Dream')
    DreamMilestone = apps.get_model('dreams', 'DreamMilestone')
    Task = apps.get_model('dreams', 'Task')

    for dream in Dream.objects.all():
        milestone_count = DreamMilestone.objects.filter(dream=dream).count()
        if milestone_count == 0:
            dream.plan_phase = 'none'
        else:
            task_count = Task.objects.filter(goal__dream=dream).count()
            if task_count == 0:
                dream.plan_phase = 'skeleton'
            else:
                dream.plan_phase = 'partial'
                latest = Task.objects.filter(goal__dream=dream).order_by('-scheduled_date').first()
                if latest and latest.scheduled_date and dream.created_at:
                    days = (latest.scheduled_date.date() - dream.created_at.date()).days
                    dream.tasks_generated_through_month = max(1, days // 30)
        dream.save(update_fields=['plan_phase', 'tasks_generated_through_month'])

    for ms in DreamMilestone.objects.all():
        has = Task.objects.filter(goal__milestone=ms).exists()
        if has:
            ms.has_tasks = True
            ms.save(update_fields=['has_tasks'])


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0017_plan_phase_and_checkins'),
    ]

    operations = [
        migrations.RunPython(backfill_plan_phase, reverse),
    ]
