# Generated by Django 5.2.11 on 2026-03-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0018_add_color_to_dream'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chain_next_delay_days',
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text='Days after completion to schedule the next task in the chain',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='chain_template_title',
            field=models.CharField(
                blank=True,
                default='',
                max_length=255,
                help_text='Custom title for the next task in the chain (uses current title if blank)',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='chain_parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='chain_children',
                to='dreams.task',
                help_text='The previous task in this chain',
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='is_chain',
            field=models.BooleanField(
                default=False,
                help_text='Whether this task is part of a recurring chain',
            ),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['chain_parent'], name='tasks_chain_p_idx'),
        ),
    ]
