# Generated by Django 5.0.14 on 2026-03-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0018_backfill_plan_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='dream',
            name='checkin_interval_days',
            field=models.IntegerField(default=14, help_text='Days between check-ins (7 if behind, 14 normal, 21 if ahead)'),
        ),
        migrations.AddField(
            model_name='plancheckin',
            name='next_checkin_interval_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='plancheckin',
            name='pace_status',
            field=models.CharField(blank=True, choices=[('significantly_behind', 'Significantly Behind'), ('behind', 'Behind'), ('on_track', 'On Track'), ('ahead', 'Ahead'), ('significantly_ahead', 'Significantly Ahead')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='plancheckin',
            name='questionnaire',
            field=models.JSONField(blank=True, help_text='AI-generated questions: [{id, question_type, question, options, ...}]', null=True),
        ),
        migrations.AddField(
            model_name='plancheckin',
            name='questionnaire_expires_at',
            field=models.DateTimeField(blank=True, help_text='After this time, check-in runs autonomously if user has not responded', null=True),
        ),
        migrations.AddField(
            model_name='plancheckin',
            name='triggered_by',
            field=models.CharField(choices=[('schedule', 'Scheduled'), ('manual', 'Manual'), ('auto_expire', 'Auto Expired')], default='schedule', max_length=20),
        ),
        migrations.AddField(
            model_name='plancheckin',
            name='user_responses',
            field=models.JSONField(blank=True, help_text='User answers: {question_id: answer_value}', null=True),
        ),
        migrations.AlterField(
            model_name='plancheckin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('questionnaire_generating', 'Generating Questionnaire'), ('awaiting_user', 'Awaiting User Response'), ('ai_processing', 'AI Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=30),
        ),
    ]
