# Generated by Django 5.2.11 on 2026-03-04 11:11

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0019_add_task_chain_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='progress_photos/')),
                ('caption', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('ai_analysis', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('taken_at', models.DateTimeField(help_text='When the progress photo was taken')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'progress_photos',
                'ordering': ['-taken_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='task',
            new_name='tasks_chain_p_306c93_idx',
            old_name='tasks_chain_p_idx',
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='dream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='dreams.dream'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['dream', '-taken_at'], name='progress_ph_dream_i_fd173a_idx'),
        ),
    ]
