# Generated by Django 5.2.11 on 2026-03-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0020_add_is_public_status_index'),
        ('dreams', '0020_add_progress_photo'),
    ]

    operations = [
    ]
