# Generated by Django 5.1.15 on 2026-03-15 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0021_merge_20260310_0205"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                help_text="The template task that spawned this recurring instance",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recurring_children",
                to="dreams.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_days",
            field=models.JSONField(
                blank=True,
                help_text='Custom recurrence days, e.g. ["mon","wed","fri"]',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_end_date",
            field=models.DateField(
                blank=True,
                help_text="Date after which no more recurring instances should be created",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_type",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                    ("custom", "Custom"),
                ],
                db_index=True,
                default="none",
                help_text="Type of recurrence pattern for this task",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="recurrence",
            field=models.JSONField(
                blank=True,
                help_text='Legacy recurrence pattern: {type: "daily|weekly|monthly", interval: 1, ...}',
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["parent_task"], name="tasks_parent__ebc03e_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["recurrence_type"], name="tasks_recurre_89ebde_idx"
            ),
        ),
    ]
