# Generated by Django 5.1.15 on 2026-03-18 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("dreams", "0021_merge_20260310_0205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plancheckin",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkin_records",
                to="ai.aiconversation",
            ),
        ),
    ]
