# Generated by Django 5.0.14 on 2026-03-20 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("rewarded", "Rewarded"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "referrals",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique invite code (auto-generated)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this referral code is currently active",
                    ),
                ),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this code can be used. Null = unlimited.",
                        null=True,
                    ),
                ),
                ("times_used", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "referral_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("xp", "XP Bonus"),
                            ("premium_days", "Premium Days"),
                            ("cosmetic", "Cosmetic Reward"),
                            ("discount", "Lifetime Discount"),
                            ("subscription_days", "Extra Subscription Days"),
                            ("streak_freeze", "Streak Freeze"),
                        ],
                        help_text="Type of reward granted",
                        max_length=30,
                    ),
                ),
                (
                    "reward_value",
                    models.IntegerField(
                        default=0,
                        help_text="Amount: XP points, premium days, discount %, or 1 for cosmetic",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "tier_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier that unlocked this reward (bronze/silver/gold/diamond)",
                        max_length=20,
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "referral_rewards",
                "ordering": ["-created_at"],
            },
        ),
    ]
