# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="referred",
            field=models.ForeignKey(
                help_text="The new user who signed up via the code.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referred_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referrer",
            field=models.ForeignKey(
                help_text="The user who shared the referral code.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralcode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_code",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="referral_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="referrals.referralcode",
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                help_text="The referral that triggered this reward (null for tier milestones)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rewards",
                to="referrals.referral",
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="user",
            field=models.ForeignKey(
                help_text="The user receiving the reward.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(fields=["code"], name="referral_co_code_0cdd0e_idx"),
        ),
        migrations.AddIndex(
            model_name="referralcode",
            index=models.Index(fields=["user"], name="referral_co_user_id_7aa554_idx"),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer", "status"], name="referrals_referre_cefb5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referred"], name="referrals_referre_e2a62f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="referral",
            constraint=models.UniqueConstraint(
                fields=("referrer", "referred"), name="unique_referral_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(
                fields=["user", "is_claimed"], name="referral_re_user_id_a611c8_idx"
            ),
        ),
    ]
