# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.core.validators
import encrypted_model_fields.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Optional personal message from the sender (encrypted at rest).",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent ID for the gift purchase.",
                        max_length=255,
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_gifts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="User-provided reason for the refund (encrypted at rest)."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "store_refund_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the category.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the category shown to users.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier or URL for the category.",
                        max_length=255,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the category appears in the store.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the category is visible in the store.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Category",
                "verbose_name_plural": "Store Categories",
                "db_table": "store_categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the store item.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the item.", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the item.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the item shown to users.",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to the item preview image.",
                        max_length=500,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Price ID for one-time payment processing.",
                        max_length=255,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the item in USD.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("badge_frame", "Badge Frame"),
                            ("theme_skin", "Theme Skin"),
                            ("avatar_decoration", "Avatar Decoration"),
                            ("chat_bubble", "Chat Bubble"),
                            ("streak_shield", "Streak Shield"),
                            ("xp_booster", "XP Booster"),
                        ],
                        db_index=True,
                        help_text="Type of cosmetic item.",
                        max_length=30,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        db_index=True,
                        default="common",
                        help_text="Rarity tier of the item affecting visual presentation.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional item metadata (e.g., colors, animation settings, duration).",
                    ),
                ),
                (
                    "preview_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("theme", "Theme"),
                            ("chat_bubble", "Chat Bubble"),
                            ("profile_bg", "Profile Background"),
                            ("avatar_frame", "Avatar Frame"),
                            ("badge", "Badge"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Type of preview experience for try-before-buy (e.g., theme, chat_bubble, avatar_frame).",
                        max_length=20,
                    ),
                ),
                (
                    "preview_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Preview configuration data (e.g., accent colors, background URLs, frame styles, bubble styles).",
                    ),
                ),
                (
                    "xp_price",
                    models.IntegerField(
                        default=0,
                        help_text="Price in XP for XP-based purchasing (0 = not purchasable with XP).",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "available_from",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of availability window (null = always available).",
                        null=True,
                    ),
                ),
                (
                    "available_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of availability window (null = always available).",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the item is available for purchase.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the item was added to the store.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Item",
                "verbose_name_plural": "Store Items",
                "db_table": "store_items",
                "ordering": ["category", "price"],
            },
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this inventory entry.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the item was purchased.",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent ID for the purchase transaction.",
                        max_length=255,
                    ),
                ),
                (
                    "is_equipped",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the item is currently equipped/active for the user.",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Inventory",
                "verbose_name_plural": "User Inventories",
                "db_table": "user_inventory",
                "ordering": ["-purchased_at"],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "store_wishlist",
                "ordering": ["-created_at"],
            },
        ),
    ]
