# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this item.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["slug"], name="store_items_slug_c7e473_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(
                fields=["item_type"], name="store_items_item_ty_231d29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["rarity"], name="store_items_rarity_57b5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(
                fields=["is_active", "item_type"], name="store_items_is_acti_e3b1a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(
                fields=["category", "is_active"], name="store_items_categor_d210af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["price"], name="store_items_price_41a568_idx"),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["user", "is_equipped"], name="user_invent_user_id_7b952c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["user", "item"], name="user_invent_user_id_61f1af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="user_invent_stripe__fbcb55_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userinventory",
            unique_together={("user", "item")},
        ),
    ]
