# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="recipient",
            field=models.ForeignKey(
                help_text="User who receives the gift.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="sender",
            field=models.ForeignKey(
                help_text="User who sent the gift.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="storecategory",
            index=models.Index(fields=["slug"], name="store_categ_slug_7ee8fd_idx"),
        ),
        migrations.AddIndex(
            model_name="storecategory",
            index=models.Index(
                fields=["is_active", "display_order"],
                name="store_categ_is_acti_0ac8c6_idx",
            ),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="category",
            field=models.ForeignKey(
                help_text="Category this item belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.storecategory",
            ),
        ),
        migrations.AddField(
            model_name="gift",
            name="item",
            field=models.ForeignKey(
                help_text="The gifted store item.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gifts",
                to="store.storeitem",
            ),
        ),
        migrations.AddField(
            model_name="userinventory",
            name="item",
            field=models.ForeignKey(
                help_text="The store item that was purchased.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owners",
                to="store.storeitem",
            ),
        ),
        migrations.AddField(
            model_name="userinventory",
            name="user",
            field=models.ForeignKey(
                help_text="User who owns this item.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="refundrequest",
            name="inventory_entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refund_requests",
                to="store.userinventory",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="store.storeitem",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["slug"], name="store_items_slug_c7e473_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(
                fields=["item_type"], name="store_items_item_ty_231d29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["rarity"], name="store_items_rarity_57b5b4_idx"),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(
                fields=["is_active", "item_type"], name="store_items_is_acti_e3b1a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(
                fields=["category", "is_active"], name="store_items_categor_d210af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storeitem",
            index=models.Index(fields=["price"], name="store_items_price_41a568_idx"),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(
                fields=["recipient", "is_claimed"],
                name="store_gifts_recipie_0f7d42_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gift",
            index=models.Index(
                fields=["sender"], name="store_gifts_sender__3d18a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["user", "is_equipped"], name="user_invent_user_id_7b952c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["user", "item"], name="user_invent_user_id_61f1af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userinventory",
            index=models.Index(
                fields=["stripe_payment_intent_id"],
                name="user_invent_stripe__fbcb55_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userinventory",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="unique_user_inventory"
            ),
        ),
        migrations.AddConstraint(
            model_name="wishlist",
            constraint=models.UniqueConstraint(
                fields=("user", "item"), name="unique_wishlist_item"
            ),
        ),
    ]
