# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_storeitem_available_from_storeitem_available_until_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gift",
            name="message",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Optional personal message from the sender (encrypted at rest).",
            ),
        ),
        migrations.AlterField(
            model_name="refundrequest",
            name="reason",
            field=encrypted_model_fields.fields.EncryptedTextField(
                help_text="User-provided reason for the refund (encrypted at rest)."
            ),
        ),
    ]
