# Generated by Django 5.2.11 on 2026-03-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_userinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict, help_text='Preview configuration data (e.g., accent colors, background URLs, frame styles, bubble styles).'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='preview_type',
            field=models.CharField(blank=True, choices=[('theme', 'Theme'), ('chat_bubble', 'Chat Bubble'), ('profile_bg', 'Profile Background'), ('avatar_frame', 'Avatar Frame'), ('badge', 'Badge')], db_index=True, default='', help_text='Type of preview experience for try-before-buy (e.g., theme, chat_bubble, avatar_frame).', max_length=20),
        ),
    ]
