# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional reason for blocking.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        help_text="The user who was blocked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        help_text="The user who performed the block.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blocked User",
                "verbose_name_plural": "Blocked Users",
                "db_table": "blocked_users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["blocker"], name="idx_blocked_blocker"),
                    models.Index(fields=["blocked"], name="idx_blocked_blocked"),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
        migrations.CreateModel(
            name="ReportedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Description of why the user is being reported."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("inappropriate", "Inappropriate Content"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category of the report.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes from admin review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reported",
                    models.ForeignKey(
                        help_text="The user being reported.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        help_text="The user who filed the report.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reported User",
                "verbose_name_plural": "Reported Users",
                "db_table": "reported_users",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status"], name="idx_report_status"),
                    models.Index(fields=["-created_at"], name="idx_report_created"),
                ],
            },
        ),
    ]
