# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leagues", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RankSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(help_text="Rank at the time of snapshot."),
                ),
                (
                    "xp",
                    models.IntegerField(
                        help_text="XP earned this season at the time of snapshot."
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(db_index=True, help_text="Date of this snapshot."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_snapshots",
                        to="leagues.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_snapshots",
                        to="leagues.season",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rank_snapshots",
                "ordering": ["-snapshot_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "season", "-snapshot_date"],
                        name="idx_snapshot_user_season_date",
                    )
                ],
                "unique_together": {("user", "season", "snapshot_date")},
            },
        ),
    ]
