# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this circle.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the circle.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the circle and its goals."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("career", "Career"),
                            ("health", "Health"),
                            ("fitness", "Fitness"),
                            ("education", "Education"),
                            ("finance", "Finance"),
                            ("creativity", "Creativity"),
                            ("relationships", "Relationships"),
                            ("personal_growth", "Personal Growth"),
                            ("hobbies", "Hobbies"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Category of the circle for discovery.",
                        max_length=30,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the circle is publicly visible and joinable.",
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        default=20,
                        help_text="Maximum number of members allowed in this circle.",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle",
                "verbose_name_plural": "Circles",
                "db_table": "circles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this challenge.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the challenge.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of the challenge."
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When this challenge starts."),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="When this challenge ends."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="upcoming",
                        help_text="Current status of the challenge.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Challenge",
                "verbose_name_plural": "Circle Challenges",
                "db_table": "circle_challenges",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this membership.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        help_text="The role of the user within the circle.",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Circle Membership",
                "verbose_name_plural": "Circle Memberships",
                "db_table": "circle_memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="CirclePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this post.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="The text content of the post."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Post",
                "verbose_name_plural": "Circle Posts",
                "db_table": "circle_posts",
                "ordering": ["-created_at"],
            },
        ),
    ]
