# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.core.validators
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChallengeProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_value",
                    models.FloatField(
                        default=0,
                        help_text="Numeric progress value (interpretation depends on challenge).",
                    ),
                ),
                (
                    "notes",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        help_text="Optional notes about this progress update (encrypted at rest).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "challenge_progress",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this circle.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the circle.", max_length=200
                    ),
                ),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        help_text="Description of the circle and its goals (encrypted at rest).",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("career", "Career"),
                            ("health", "Health"),
                            ("fitness", "Fitness"),
                            ("education", "Education"),
                            ("finance", "Finance"),
                            ("creativity", "Creativity"),
                            ("relationships", "Relationships"),
                            ("personal_growth", "Personal Growth"),
                            ("hobbies", "Hobbies"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        help_text="Category of the circle for discovery.",
                        max_length=30,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the circle is publicly visible and joinable.",
                    ),
                ),
                (
                    "max_members",
                    models.IntegerField(
                        default=20,
                        help_text="Maximum number of members allowed in this circle.",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle",
                "verbose_name_plural": "Circles",
                "db_table": "circles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleCall",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("voice", "Voice"), ("video", "Video")],
                        default="voice",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=15,
                    ),
                ),
                (
                    "agora_channel",
                    models.CharField(
                        help_text="Agora channel name (= str(call.id)).", max_length=100
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("max_participants", models.IntegerField(default=20)),
            ],
            options={
                "db_table": "circle_calls",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleCallParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "circle_call_participants",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this challenge.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the challenge.", max_length=200
                    ),
                ),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        help_text="Detailed description of the challenge (encrypted at rest).",
                    ),
                ),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("tasks_completed", "Complete Tasks"),
                            ("streak_days", "Maintain Streak"),
                            ("focus_minutes", "Focus Minutes"),
                            ("dreams_progress", "Dream Progress"),
                        ],
                        default="tasks_completed",
                        help_text="Type of challenge determining how progress is measured.",
                        max_length=50,
                    ),
                ),
                (
                    "target_value",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Target value participants must reach to complete the challenge.",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When this challenge starts."),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="When this challenge ends."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="upcoming",
                        help_text="Current status of the challenge.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Challenge",
                "verbose_name_plural": "Circle Challenges",
                "db_table": "circle_challenges",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CircleInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        db_index=True,
                        help_text="Shareable code for link-based invitations.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "circle_invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this membership.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("moderator", "Moderator"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        help_text="The role of the user within the circle.",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Circle Membership",
                "verbose_name_plural": "Circle Memberships",
                "db_table": "circle_memberships",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.CreateModel(
            name="CircleMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Message content (encrypted at rest)."
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "circle_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CirclePoll",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this poll.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.CharField(help_text="The poll question.", max_length=300),
                ),
                (
                    "allows_multiple",
                    models.BooleanField(
                        default=False,
                        help_text="Whether users can vote for multiple options.",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When voting closes (null = no deadline).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Circle Poll",
                "verbose_name_plural": "Circle Polls",
                "db_table": "circle_polls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CirclePost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this post.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="The text content of the post (encrypted at rest)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Circle Post",
                "verbose_name_plural": "Circle Posts",
                "db_table": "circle_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this option.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    models.CharField(help_text="The option text.", max_length=200),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order (ascending)."
                    ),
                ),
            ],
            options={
                "verbose_name": "Poll Option",
                "verbose_name_plural": "Poll Options",
                "db_table": "poll_options",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this vote.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Poll Vote",
                "verbose_name_plural": "Poll Votes",
                "db_table": "poll_votes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("thumbs_up", "Thumbs Up"),
                            ("fire", "Fire"),
                            ("clap", "Clap"),
                            ("heart", "Heart"),
                        ],
                        help_text="Type of reaction.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Post Reaction",
                "verbose_name_plural": "Post Reactions",
                "db_table": "post_reactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
