# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="challengeprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenge_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circle",
            name="creator",
            field=models.ForeignKey(
                help_text="The user who created this circle.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_circles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlecall",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calls",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlecall",
            name="initiator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_calls_initiated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlecallparticipant",
            name="call",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="circles.circlecall",
            ),
        ),
        migrations.AddField(
            model_name="circlecallparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_call_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlechallenge",
            name="circle",
            field=models.ForeignKey(
                help_text="The circle this challenge belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlechallenge",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who created this challenge.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlechallenge",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have joined this challenge.",
                related_name="circle_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="challengeprogress",
            name="challenge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_entries",
                to="circles.circlechallenge",
            ),
        ),
        migrations.AddField(
            model_name="circleinvitation",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circleinvitation",
            name="invitee",
            field=models.ForeignKey(
                blank=True,
                help_text="The user invited (null for link invitations).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_invites_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circleinvitation",
            name="inviter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_invites_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="circle",
            field=models.ForeignKey(
                help_text="The circle this membership belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="user",
            field=models.ForeignKey(
                help_text="The user who is a member of the circle.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlemessage",
            name="circle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlemessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="author",
            field=models.ForeignKey(
                help_text="The user who created this post.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="circle",
            field=models.ForeignKey(
                help_text="The circle this post belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlepoll",
            name="post",
            field=models.OneToOneField(
                help_text="The circle post this poll belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="circles.circlepost",
            ),
        ),
        migrations.AddField(
            model_name="polloption",
            name="poll",
            field=models.ForeignKey(
                help_text="The poll this option belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="circles.circlepoll",
            ),
        ),
        migrations.AddField(
            model_name="pollvote",
            name="option",
            field=models.ForeignKey(
                help_text="The option that was voted for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="circles.polloption",
            ),
        ),
        migrations.AddField(
            model_name="pollvote",
            name="user",
            field=models.ForeignKey(
                help_text="The user who cast this vote.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                help_text="The post this reaction is on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="circles.circlepost",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="user",
            field=models.ForeignKey(
                help_text="The user who reacted.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["category"], name="idx_circle_category"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["is_public"], name="idx_circle_public"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["creator"], name="idx_circle_creator"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["-created_at"], name="idx_circle_created"),
        ),
        migrations.AddIndex(
            model_name="circlecall",
            index=models.Index(
                fields=["circle", "status"], name="idx_circlecall_circle_status"
            ),
        ),
        migrations.AddIndex(
            model_name="circlecall",
            index=models.Index(fields=["status"], name="idx_circlecall_status"),
        ),
        migrations.AddConstraint(
            model_name="circlecallparticipant",
            constraint=models.UniqueConstraint(
                fields=("call", "user"), name="unique_call_participant"
            ),
        ),
        migrations.AddIndex(
            model_name="circlechallenge",
            index=models.Index(
                fields=["circle", "status"], name="idx_challenge_circle_status"
            ),
        ),
        migrations.AddIndex(
            model_name="circlechallenge",
            index=models.Index(fields=["status"], name="idx_challenge_status"),
        ),
        migrations.AddIndex(
            model_name="circlechallenge",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_challenge_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="challengeprogress",
            index=models.Index(
                fields=["challenge", "user", "-created_at"],
                name="challenge_p_challen_73dc1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="circleinvitation",
            index=models.Index(
                fields=["invite_code"], name="circle_invi_invite__0062a8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="circleinvitation",
            index=models.Index(
                fields=["circle", "invitee", "status"],
                name="circle_invi_circle__cc96c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(
                fields=["circle", "user"], name="idx_membership_circle_user"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["user"], name="idx_membership_user"),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["circle", "role"], name="idx_membership_role"),
        ),
        migrations.AddConstraint(
            model_name="circlemembership",
            constraint=models.UniqueConstraint(
                fields=("circle", "user"), name="unique_circle_membership"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemessage",
            index=models.Index(
                fields=["circle", "created_at"], name="idx_circlemsg_circle_date"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemessage",
            index=models.Index(fields=["sender"], name="idx_circlemsg_sender"),
        ),
        migrations.AddIndex(
            model_name="circlepost",
            index=models.Index(
                fields=["circle", "-created_at"], name="idx_post_circle_date"
            ),
        ),
        migrations.AddIndex(
            model_name="circlepost",
            index=models.Index(fields=["author"], name="idx_post_author"),
        ),
        migrations.AddIndex(
            model_name="circlepoll",
            index=models.Index(fields=["post"], name="idx_poll_post"),
        ),
        migrations.AddIndex(
            model_name="polloption",
            index=models.Index(
                fields=["poll", "order"], name="idx_polloption_poll_order"
            ),
        ),
        migrations.AddIndex(
            model_name="pollvote",
            index=models.Index(
                fields=["option", "user"], name="idx_pollvote_option_user"
            ),
        ),
        migrations.AddIndex(
            model_name="pollvote",
            index=models.Index(fields=["user"], name="idx_pollvote_user"),
        ),
        migrations.AddConstraint(
            model_name="pollvote",
            constraint=models.UniqueConstraint(
                fields=("option", "user"), name="unique_poll_vote"
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(
                fields=["post", "reaction_type"], name="idx_reaction_post_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="postreaction",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_post_reaction"
            ),
        ),
    ]
