# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("circles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="circle",
            name="creator",
            field=models.ForeignKey(
                help_text="The user who created this circle.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_circles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlechallenge",
            name="circle",
            field=models.ForeignKey(
                help_text="The circle this challenge belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="challenges",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlechallenge",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who have joined this challenge.",
                related_name="circle_challenges",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="circle",
            field=models.ForeignKey(
                help_text="The circle this membership belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="circles.circle",
            ),
        ),
        migrations.AddField(
            model_name="circlemembership",
            name="user",
            field=models.ForeignKey(
                help_text="The user who is a member of the circle.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="author",
            field=models.ForeignKey(
                help_text="The user who created this post.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="circle_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="circlepost",
            name="circle",
            field=models.ForeignKey(
                help_text="The circle this post belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="circles.circle",
            ),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["category"], name="idx_circle_category"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["is_public"], name="idx_circle_public"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["creator"], name="idx_circle_creator"),
        ),
        migrations.AddIndex(
            model_name="circle",
            index=models.Index(fields=["-created_at"], name="idx_circle_created"),
        ),
        migrations.AddIndex(
            model_name="circlechallenge",
            index=models.Index(
                fields=["circle", "status"], name="idx_challenge_circle_status"
            ),
        ),
        migrations.AddIndex(
            model_name="circlechallenge",
            index=models.Index(fields=["status"], name="idx_challenge_status"),
        ),
        migrations.AddIndex(
            model_name="circlechallenge",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_challenge_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(
                fields=["circle", "user"], name="idx_membership_circle_user"
            ),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["user"], name="idx_membership_user"),
        ),
        migrations.AddIndex(
            model_name="circlemembership",
            index=models.Index(fields=["circle", "role"], name="idx_membership_role"),
        ),
        migrations.AlterUniqueTogether(
            name="circlemembership",
            unique_together={("circle", "user")},
        ),
        migrations.AddIndex(
            model_name="circlepost",
            index=models.Index(
                fields=["circle", "-created_at"], name="idx_post_circle_date"
            ),
        ),
        migrations.AddIndex(
            model_name="circlepost",
            index=models.Index(fields=["author"], name="idx_post_author"),
        ),
    ]
