# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0003_challengeprogress_circleinvitation_postreaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengeprogress",
            name="notes",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Optional notes about this progress update (encrypted at rest).",
            ),
        ),
        migrations.AlterField(
            model_name="circle",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Description of the circle and its goals (encrypted at rest).",
            ),
        ),
        migrations.AlterField(
            model_name="circlechallenge",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                help_text="Detailed description of the challenge (encrypted at rest).",
            ),
        ),
        migrations.AlterField(
            model_name="circlepost",
            name="content",
            field=encrypted_model_fields.fields.EncryptedTextField(
                help_text="The text content of the post (encrypted at rest)."
            ),
        ),
    ]
