# Generated by Django 5.2.11 on 2026-02-27 03:40

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_alter_challengeprogress_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CircleCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('voice', 'Voice'), ('video', 'Video')], default='voice', max_length=5)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=15)),
                ('agora_channel', models.CharField(help_text='Agora channel name (= str(call.id)).', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('max_participants', models.IntegerField(default=20)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='circles.circle')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_calls_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_calls',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleCallParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='circles.circlecall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_call_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_call_participants',
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='CircleMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', encrypted_model_fields.fields.EncryptedTextField(help_text='Message content (encrypted at rest).')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='circles.circle')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'circle_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='circlecall',
            index=models.Index(fields=['circle', 'status'], name='idx_circlecall_circle_status'),
        ),
        migrations.AddIndex(
            model_name='circlecall',
            index=models.Index(fields=['status'], name='idx_circlecall_status'),
        ),
        migrations.AlterUniqueTogether(
            name='circlecallparticipant',
            unique_together={('call', 'user')},
        ),
        migrations.AddIndex(
            model_name='circlemessage',
            index=models.Index(fields=['circle', 'created_at'], name='idx_circlemsg_circle_date'),
        ),
        migrations.AddIndex(
            model_name='circlemessage',
            index=models.Index(fields=['sender'], name='idx_circlemsg_sender'),
        ),
    ]
