# Generated by Django 5.2.11 on 2026-02-27 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_circlecall_circlecallparticipant_circlemessage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='circlecallparticipant',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='circlemembership',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='circlecallparticipant',
            constraint=models.UniqueConstraint(fields=('call', 'user'), name='unique_call_participant'),
        ),
        migrations.AddConstraint(
            model_name='circlemembership',
            constraint=models.UniqueConstraint(fields=('circle', 'user'), name='unique_circle_membership'),
        ),
        migrations.AddConstraint(
            model_name='postreaction',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_post_reaction'),
        ),
    ]
