# Generated by Django 5.2.11 on 2026-03-04 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0006_alter_circlecallparticipant_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circlechallenge',
            name='challenge_type',
            field=models.CharField(choices=[('tasks_completed', 'Complete Tasks'), ('streak_days', 'Maintain Streak'), ('focus_minutes', 'Focus Minutes'), ('dreams_progress', 'Dream Progress')], default='tasks_completed', help_text='Type of challenge determining how progress is measured.', max_length=50),
        ),
        migrations.AddField(
            model_name='circlechallenge',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user who created this challenge.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circlechallenge',
            name='target_value',
            field=models.PositiveIntegerField(default=0, help_text='Target value participants must reach to complete the challenge.'),
        ),
    ]
