# Generated by Django 5.0.1 on 2026-03-04 09:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0007_circlechallenge_challenge_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CirclePoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this poll.', primary_key=True, serialize=False)),
                ('question', models.CharField(help_text='The poll question.', max_length=300)),
                ('allows_multiple', models.BooleanField(default=False, help_text='Whether users can vote for multiple options.')),
                ('ends_at', models.DateTimeField(blank=True, help_text='When voting closes (null = no deadline).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.OneToOneField(help_text='The circle post this poll belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='circles.circlepost')),
            ],
            options={
                'verbose_name': 'Circle Poll',
                'verbose_name_plural': 'Circle Polls',
                'db_table': 'circle_polls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this option.', primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='The option text.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (ascending).')),
                ('poll', models.ForeignKey(help_text='The poll this option belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='circles.circlepoll')),
            ],
            options={
                'verbose_name': 'Poll Option',
                'verbose_name_plural': 'Poll Options',
                'db_table': 'poll_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this vote.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(help_text='The option that was voted for.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='circles.polloption')),
                ('user', models.ForeignKey(help_text='The user who cast this vote.', on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poll Vote',
                'verbose_name_plural': 'Poll Votes',
                'db_table': 'poll_votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='circlepoll',
            index=models.Index(fields=['post'], name='idx_poll_post'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'order'], name='idx_polloption_poll_order'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['option', 'user'], name='idx_pollvote_option_user'),
        ),
        migrations.AddIndex(
            model_name='pollvote',
            index=models.Index(fields=['user'], name='idx_pollvote_user'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('option', 'user'), name='unique_poll_vote'),
        ),
    ]
