# Generated by Django 5.0.14 on 2026-03-20 19:09

import apps.updates.models
import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppBundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bundle_id",
                    models.CharField(
                        default=apps.updates.models._generate_bundle_id,
                        help_text="Auto-generated unique identifier (e.g. b-20260308-153045)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "min_app_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Minimum native versionCode required to apply this bundle",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("all", "All platforms"),
                            ("android", "Android only"),
                            ("ios", "iOS only"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("silent", "Silent — apply on next restart"),
                            ("notify", "Notify — show user a restart prompt"),
                        ],
                        default="notify",
                        max_length=10,
                    ),
                ),
                (
                    "bundle_file",
                    models.FileField(
                        help_text="The zipped web bundle (dist/)",
                        storage=core.storage.ReleasesStorage,
                        upload_to=apps.updates.models._bundle_upload_path,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hex digest of the zip file (auto-computed on upload)",
                        max_length=128,
                    ),
                ),
                (
                    "signature",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="RSA signature of the checksum (base64, for code signing)",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional message to show with notify strategy",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active bundles are served to clients",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "App Bundle",
                "verbose_name_plural": "App Bundles",
                "ordering": ["-created_at"],
            },
        ),
    ]
