# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuddyEncouragement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this encouragement.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional motivational message.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Buddy Encouragement",
                "verbose_name_plural": "Buddy Encouragements",
                "db_table": "buddy_encouragements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuddyPairing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this buddy pairing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the buddy pairing.",
                        max_length=20,
                    ),
                ),
                (
                    "compatibility_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Compatibility score between 0.0 and 1.0, calculated at match time.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the pairing ended (completed or cancelled).",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Buddy Pairing",
                "verbose_name_plural": "Buddy Pairings",
                "db_table": "buddy_pairings",
                "ordering": ["-created_at"],
            },
        ),
    ]
