# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.core.validators
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountabilityContract",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this contract.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the accountability contract.",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the contract."
                    ),
                ),
                (
                    "goals",
                    models.JSONField(
                        default=list,
                        help_text="List of goals: [{title, target, unit}].",
                    ),
                ),
                (
                    "check_in_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                        ],
                        default="weekly",
                        help_text="How often partners should check in.",
                        max_length=20,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="When the contract period begins."),
                ),
                (
                    "end_date",
                    models.DateField(help_text="When the contract period ends."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        help_text="Current status of the contract.",
                        max_length=20,
                    ),
                ),
                (
                    "accepted_by_partner",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the partner has accepted this contract.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Accountability Contract",
                "verbose_name_plural": "Accountability Contracts",
                "db_table": "buddy_contracts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuddyEncouragement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this encouragement.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Optional motivational message (encrypted at rest).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Buddy Encouragement",
                "verbose_name_plural": "Buddy Encouragements",
                "db_table": "buddy_encouragements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BuddyPairing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this buddy pairing.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the buddy pairing.",
                        max_length=20,
                    ),
                ),
                (
                    "compatibility_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Compatibility score between 0.0 and 1.0, calculated at match time.",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "encouragement_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Current consecutive-day encouragement streak.",
                    ),
                ),
                (
                    "best_encouragement_streak",
                    models.IntegerField(
                        default=0,
                        help_text="Best-ever consecutive-day encouragement streak.",
                    ),
                ),
                (
                    "last_encouragement_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the last encouragement sent in this pairing.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the pairing ended (completed or cancelled).",
                        null=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When a pending buddy request expires (auto-cancelled after 7 days).",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Buddy Pairing",
                "verbose_name_plural": "Buddy Pairings",
                "db_table": "buddy_pairings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContractCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this check-in.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress",
                    models.JSONField(
                        default=dict,
                        help_text="Progress values keyed by goal index: {goal_index: value}.",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Optional note accompanying the check-in."
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True,
                        help_text="User mood at time of check-in.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Contract Check-In",
                "verbose_name_plural": "Contract Check-Ins",
                "db_table": "buddy_contract_check_ins",
                "ordering": ["-created_at"],
            },
        ),
    ]
