# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buddies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accountabilitycontract",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created this contract.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_contracts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buddyencouragement",
            name="sender",
            field=models.ForeignKey(
                help_text="The user who sent the encouragement.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_encouragements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buddypairing",
            name="user1",
            field=models.ForeignKey(
                help_text="The first user in the pairing (initiator).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buddy_pairings_as_user1",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buddypairing",
            name="user2",
            field=models.ForeignKey(
                help_text="The second user in the pairing (matched partner).",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buddy_pairings_as_user2",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="buddyencouragement",
            name="pairing",
            field=models.ForeignKey(
                help_text="The buddy pairing this encouragement belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encouragements",
                to="buddies.buddypairing",
            ),
        ),
        migrations.AddField(
            model_name="accountabilitycontract",
            name="pairing",
            field=models.ForeignKey(
                help_text="The buddy pairing this contract belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="buddies.buddypairing",
            ),
        ),
        migrations.AddField(
            model_name="contractcheckin",
            name="contract",
            field=models.ForeignKey(
                help_text="The contract this check-in belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_ins",
                to="buddies.accountabilitycontract",
            ),
        ),
        migrations.AddField(
            model_name="contractcheckin",
            name="user",
            field=models.ForeignKey(
                help_text="The user who submitted this check-in.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_check_ins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="buddypairing",
            index=models.Index(
                fields=["user1", "status"], name="idx_buddy_user1_status"
            ),
        ),
        migrations.AddIndex(
            model_name="buddypairing",
            index=models.Index(
                fields=["user2", "status"], name="idx_buddy_user2_status"
            ),
        ),
        migrations.AddIndex(
            model_name="buddypairing",
            index=models.Index(fields=["status"], name="idx_buddy_status"),
        ),
        migrations.AddIndex(
            model_name="buddypairing",
            index=models.Index(fields=["-created_at"], name="idx_buddy_created"),
        ),
        migrations.AddIndex(
            model_name="buddyencouragement",
            index=models.Index(
                fields=["pairing", "-created_at"], name="idx_encourage_pairing"
            ),
        ),
        migrations.AddIndex(
            model_name="buddyencouragement",
            index=models.Index(fields=["sender"], name="idx_encourage_sender"),
        ),
        migrations.AddIndex(
            model_name="accountabilitycontract",
            index=models.Index(
                fields=["pairing", "status"], name="idx_contract_pairing_status"
            ),
        ),
        migrations.AddIndex(
            model_name="accountabilitycontract",
            index=models.Index(fields=["created_by"], name="idx_contract_created_by"),
        ),
        migrations.AddIndex(
            model_name="accountabilitycontract",
            index=models.Index(fields=["-created_at"], name="idx_contract_created"),
        ),
        migrations.AddIndex(
            model_name="contractcheckin",
            index=models.Index(
                fields=["contract", "user"], name="idx_checkin_contract_user"
            ),
        ),
        migrations.AddIndex(
            model_name="contractcheckin",
            index=models.Index(
                fields=["contract", "-created_at"], name="idx_checkin_contract_date"
            ),
        ),
    ]
