# Generated by Django 5.2.6 on 2026-02-24 07:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0003_buddypairing_best_encouragement_streak_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buddyencouragement",
            name="message",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Optional motivational message (encrypted at rest).",
            ),
        ),
    ]
