# Generated by Django 5.2.11 on 2026-02-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0004_alter_buddyencouragement_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='buddypairing',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When a pending buddy request expires (auto-cancelled after 7 days).', null=True),
        ),
    ]
