# Generated by Django 5.2.11 on 2026-03-04 05:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddies', '0005_buddypairing_expires_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this contract.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the accountability contract.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the contract.')),
                ('goals', models.JSONField(default=list, help_text='List of goals: [{title, target, unit}].')),
                ('check_in_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly')], default='weekly', help_text='How often partners should check in.', max_length=20)),
                ('start_date', models.DateField(help_text='When the contract period begins.')),
                ('end_date', models.DateField(help_text='When the contract period ends.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', help_text='Current status of the contract.', max_length=20)),
                ('accepted_by_partner', models.BooleanField(default=False, help_text='Whether the partner has accepted this contract.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='The user who created this contract.', on_delete=django.db.models.deletion.CASCADE, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('pairing', models.ForeignKey(help_text='The buddy pairing this contract belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='buddies.buddypairing')),
            ],
            options={
                'verbose_name': 'Accountability Contract',
                'verbose_name_plural': 'Accountability Contracts',
                'db_table': 'buddy_contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractCheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this check-in.', primary_key=True, serialize=False)),
                ('progress', models.JSONField(default=dict, help_text='Progress values keyed by goal index: {goal_index: value}.')),
                ('note', models.TextField(blank=True, help_text='Optional note accompanying the check-in.')),
                ('mood', models.CharField(blank=True, help_text='User mood at time of check-in.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(help_text='The contract this check-in belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='buddies.accountabilitycontract')),
                ('user', models.ForeignKey(help_text='The user who submitted this check-in.', on_delete=django.db.models.deletion.CASCADE, related_name='contract_check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Check-In',
                'verbose_name_plural': 'Contract Check-Ins',
                'db_table': 'buddy_contract_check_ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accountabilitycontract',
            index=models.Index(fields=['pairing', 'status'], name='idx_contract_pairing_status'),
        ),
        migrations.AddIndex(
            model_name='accountabilitycontract',
            index=models.Index(fields=['created_by'], name='idx_contract_created_by'),
        ),
        migrations.AddIndex(
            model_name='accountabilitycontract',
            index=models.Index(fields=['-created_at'], name='idx_contract_created'),
        ),
        migrations.AddIndex(
            model_name='contractcheckin',
            index=models.Index(fields=['contract', 'user'], name='idx_checkin_contract_user'),
        ),
        migrations.AddIndex(
            model_name='contractcheckin',
            index=models.Index(fields=['contract', '-created_at'], name='idx_checkin_contract_date'),
        ),
    ]
