# Generated by Django 5.1.15 on 2026-03-15 03:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0006_accountabilitycontract_contractcheckin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuddySkip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this skip record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skipped_user",
                    models.ForeignKey(
                        help_text="The user who was skipped.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skipped_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who performed the skip.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buddy_skips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Buddy Skip",
                "verbose_name_plural": "Buddy Skips",
                "db_table": "buddy_skips",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_buddy_skip_user"),
                    models.Index(
                        fields=["skipped_user"], name="idx_buddy_skip_skipped"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "skipped_user"), name="unique_buddy_skip"
                    )
                ],
            },
        ),
    ]
