# Generated by Django 5.0.14 on 2026-03-20 19:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Lucide icon name (e.g. sparkles, flame, trophy)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("streaks", "Streaks"),
                            ("dreams", "Dreams"),
                            ("social", "Social"),
                            ("tasks", "Tasks"),
                            ("special", "Special"),
                            ("profile", "Profile"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        db_index=True,
                        default="common",
                        help_text="Rarity tier that determines badge glow color.",
                        max_length=20,
                    ),
                ),
                ("xp_reward", models.IntegerField(default=0)),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("streak_days", "Streak Days"),
                            ("dreams_created", "Dreams Created"),
                            ("dreams_completed", "Dreams Completed"),
                            ("tasks_completed", "Tasks Completed"),
                            ("friends_count", "Friends Count"),
                            ("circles_joined", "Circles Joined"),
                            ("level_reached", "Level Reached"),
                            ("xp_earned", "XP Earned"),
                            ("early_task", "Early Task (before 8am)"),
                            ("late_task", "Late Task (after 10pm)"),
                            ("first_dream", "First Dream Created"),
                            ("first_buddy", "First Buddy Matched"),
                            ("vision_created", "Vision Board Created"),
                            ("posts_created", "Posts Created"),
                            ("likes_received", "Likes Received"),
                            ("profile_completed", "Profile Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "condition_value",
                    models.IntegerField(
                        default=1, help_text="Threshold value to unlock"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "achievements",
                "ordering": ["category", "condition_value"],
            },
        ),
        migrations.CreateModel(
            name="DailyActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("tasks_completed", models.IntegerField(default=0)),
                ("xp_earned", models.IntegerField(default=0)),
                ("minutes_active", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "daily_activities",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="GamificationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("health_xp", models.IntegerField(default=0)),
                ("career_xp", models.IntegerField(default=0)),
                ("relationships_xp", models.IntegerField(default=0)),
                ("personal_growth_xp", models.IntegerField(default=0)),
                ("finance_xp", models.IntegerField(default=0)),
                ("hobbies_xp", models.IntegerField(default=0)),
                ("badges", models.JSONField(blank=True, default=list)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("streak_jokers", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gamification_profiles",
            },
        ),
        migrations.CreateModel(
            name="HabitChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check-in"),
                            ("task_completion", "Task Completion"),
                            ("focus_timer", "Focus Timer"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "habit_chains",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "progress",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current progress towards the achievement requirement value.",
                    ),
                ),
            ],
            options={
                "db_table": "user_achievements",
                "ordering": ["-unlocked_at"],
            },
        ),
    ]
