# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0002_initial"),
        ("gamification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gamificationprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gamification",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitchain",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habit_chains",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="habitchain",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habit_chains",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="achievement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_achievements",
                to="gamification.achievement",
            ),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_achievements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="dailyactivity",
            index=models.Index(
                fields=["user", "-date"], name="daily_activ_user_id_cd76b0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dailyactivity",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="unique_daily_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="habitchain",
            index=models.Index(
                fields=["user", "-date"], name="habit_chain_user_id_52d2a5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habitchain",
            index=models.Index(
                fields=["user", "chain_type", "-date"],
                name="habit_chain_user_id_862b5f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userachievement",
            constraint=models.UniqueConstraint(
                fields=("user", "achievement"), name="unique_user_achievement"
            ),
        ),
    ]
