# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="parent_event",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent event if this is a recurring instance.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_instances",
                to="calendar.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="recurrence_rule",
            field=models.JSONField(
                blank=True,
                help_text='Recurrence rule: {frequency: "daily|weekly|monthly", interval: 1, end_date: "ISO"}',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="GoogleCalendarIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("token_expiry", models.DateTimeField()),
                (
                    "calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="Google Calendar ID to sync with.",
                        max_length=255,
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_token",
                    models.CharField(
                        blank=True,
                        help_text="Google incremental sync token.",
                        max_length=500,
                    ),
                ),
                (
                    "ical_feed_token",
                    models.CharField(
                        blank=True,
                        help_text="Secret token for iCal feed URL.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_calendar",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "google_calendar_integrations",
            },
        ),
    ]
