# Generated by Django 5.2.11 on 2026-03-10 10:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category display name.', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Short description of the category.')),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji or icon name for the category (e.g., a Lucide icon name).', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Display order (ascending).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'blog_categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Tag display name.', max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'blog_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Post title.', max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (must be unique).', max_length=280, unique=True)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Short summary displayed in list views.')),
                ('content', models.TextField(help_text='Full post content (Markdown or HTML).')),
                ('cover_image', models.URLField(blank=True, default='', help_text='Cover image URL (e.g., Unsplash).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Publication status.', max_length=10)),
                ('featured', models.BooleanField(db_index=True, default=False, help_text='Whether this post is featured/highlighted.')),
                ('read_time_minutes', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes.')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of times this post has been viewed.')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='When the post was (or will be) published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='The user who authored this post.', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Primary category for this post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with this post.', related_name='posts', to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'blog_posts',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='idx_blogpost_status_pub'), models.Index(fields=['category', '-published_at'], name='idx_blogpost_cat_pub'), models.Index(fields=['featured', '-published_at'], name='idx_blogpost_featured_pub'), models.Index(fields=['-created_at'], name='idx_blogpost_created'), models.Index(fields=['author', '-published_at'], name='idx_blogpost_author_pub')],
            },
        ),
    ]
