# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe customer ID (cus_xxxxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stripe_customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "stripe_webhook_events",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Stripe Subscription ID (sub_xxxxx). Empty for free-tier subscriptions.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("trialing", "Trialing"),
                            ("unpaid", "Unpaid"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="incomplete",
                        max_length=30,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="If True, subscription cancels at end of current period",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user requested cancellation",
                        null=True,
                    ),
                ),
                (
                    "pending_plan_effective_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the pending plan change takes effect",
                        null=True,
                    ),
                ),
                (
                    "stripe_schedule_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe SubscriptionSchedule ID for pending downgrades",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Plan display name (Free, Premium, Pro)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe plan identifier (free, premium, pro)",
                        unique=True,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Price ID (price_xxxxx). Empty for free tier.",
                        max_length=255,
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly price in USD",
                        max_digits=6,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object describing plan features for display",
                    ),
                ),
                (
                    "dream_limit",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum active dreams allowed. -1 for unlimited.",
                    ),
                ),
                (
                    "has_ai",
                    models.BooleanField(
                        default=False, help_text="Access to AI coaching features"
                    ),
                ),
                (
                    "has_buddy",
                    models.BooleanField(
                        default=False, help_text="Access to Dream Buddy matching"
                    ),
                ),
                (
                    "has_circles",
                    models.BooleanField(
                        default=False,
                        help_text="Access to Dream Circles (group accountability)",
                    ),
                ),
                (
                    "has_vision_board",
                    models.BooleanField(
                        default=False, help_text="Access to AI Vision Board generation"
                    ),
                ),
                (
                    "has_league",
                    models.BooleanField(
                        default=False, help_text="Access to competitive leagues"
                    ),
                ),
                (
                    "has_store",
                    models.BooleanField(
                        default=False, help_text="Access to store purchases"
                    ),
                ),
                (
                    "has_social_feed",
                    models.BooleanField(
                        default=False, help_text="Access to the social activity feed"
                    ),
                ),
                (
                    "has_circle_create",
                    models.BooleanField(
                        default=False,
                        help_text="Can create new circles (separate from joining)",
                    ),
                ),
                (
                    "has_public_dreams",
                    models.BooleanField(
                        default=False,
                        help_text="Can make dreams publicly visible to other users",
                    ),
                ),
                (
                    "has_ads",
                    models.BooleanField(
                        default=True,
                        help_text="Whether ads are shown to users on this plan",
                    ),
                ),
                (
                    "ai_chat_daily_limit",
                    models.IntegerField(
                        default=0,
                        help_text="Daily AI chat messages limit. 0=no access.",
                    ),
                ),
                (
                    "ai_plan_daily_limit",
                    models.IntegerField(
                        default=0, help_text="Daily AI plan/analysis operations limit."
                    ),
                ),
                (
                    "ai_image_daily_limit",
                    models.IntegerField(
                        default=0, help_text="Daily AI image generation limit (DALL-E)."
                    ),
                ),
                (
                    "ai_voice_daily_limit",
                    models.IntegerField(
                        default=0, help_text="Daily voice transcription limit."
                    ),
                ),
                (
                    "ai_background_daily_limit",
                    models.IntegerField(
                        default=3,
                        help_text="Daily background AI tasks limit (motivation, reports).",
                    ),
                ),
                (
                    "ai_calibration_daily_limit",
                    models.IntegerField(
                        default=0,
                        help_text="Daily calibration questions limit. 0=no access.",
                    ),
                ),
                (
                    "trial_period_days",
                    models.IntegerField(
                        default=0,
                        help_text="Number of free trial days for new subscribers (0 = no trial)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this promotion", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Public-facing description shown to users",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the promotion becomes available"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline to redeem the promotion. After this date, users can no longer use it.",
                        null=True,
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many months the discount lasts after redemption (e.g. 2, 3, 4 months).",
                        null=True,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        help_text="Whether the discount is a percentage or fixed dollar amount",
                        max_length=20,
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total redemptions. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("none", "None (everyone)"),
                            ("email_endswith", "Email Ends With"),
                        ],
                        default="none",
                        help_text="Eligibility condition type",
                        max_length=30,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Condition value (e.g. '@school.ca' for email_endswith)",
                        max_length=100,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[("all", "All Users"), ("new_users", "New Users Only")],
                        default="all",
                        help_text="Who can see and redeem this promotion",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Admin toggle to enable/disable the promotion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "promotions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="promotions_is_acti_dbec31_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionPlanDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed dollar amount, per promotion.discount_type",
                        max_digits=8,
                    ),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-created Stripe coupon ID (do not edit manually)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_discounts",
                        to="subscriptions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_plan_discounts",
            },
        ),
        migrations.CreateModel(
            name="PromotionChangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("coupon_created", "Coupon Created"),
                            ("coupon_recreated", "Coupon Recreated"),
                            ("coupon_deleted", "Coupon Deleted"),
                            ("promotion_updated", "Promotion Updated"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "old_stripe_coupon_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "new_stripe_coupon_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, help_text="Snapshot of changed values"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_logs",
                        to="subscriptions.promotion",
                    ),
                ),
                (
                    "plan_discount",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_logs",
                        to="subscriptions.promotionplandiscount",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_change_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(
                        help_text="The Stripe coupon ID used for this redemption",
                        max_length=255,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="subscriptions.promotion",
                    ),
                ),
                (
                    "promotion_plan_discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="subscriptions.promotionplandiscount",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_redemptions",
            },
        ),
    ]
