# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="promotionredemption",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_redemptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stripecustomer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stripe_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="stripewebhookevent",
            index=models.Index(
                fields=["stripe_event_id"], name="stripe_webh_stripe__e9e10a_idx"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="active_subscription",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan the user is downgrading to (takes effect at period end)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscriptions",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddField(
            model_name="promotionplandiscount",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_discounts",
                to="subscriptions.subscriptionplan",
            ),
        ),
        migrations.AddIndex(
            model_name="promotionredemption",
            index=models.Index(
                fields=["promotion", "user"], name="promotion_r_promoti_df7ca3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotionredemption",
            unique_together={("promotion", "user")},
        ),
        migrations.AddIndex(
            model_name="stripecustomer",
            index=models.Index(
                fields=["stripe_customer_id"], name="stripe_cust_stripe__2ea2de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["stripe_subscription_id"], name="subscriptio_stripe__aa726e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(fields=["status"], name="subscriptio_status_572d44_idx"),
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "status"], name="subscriptio_user_id_8d58fd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="promotionplandiscount",
            unique_together={("promotion", "plan")},
        ),
    ]
