# Generated by Django 5.2.6 on 2026-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="trial_period_days",
            field=models.IntegerField(
                default=0,
                help_text="Number of free trial days for new subscribers (0 = no trial)",
            ),
        ),
    ]
