# Generated by Django 5.0.6 on 2026-02-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_trial_period_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_background_daily_limit',
            field=models.IntegerField(default=3, help_text='Daily background AI tasks limit (motivation, reports).'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_chat_daily_limit',
            field=models.IntegerField(default=0, help_text='Daily AI chat messages limit. 0=no access.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_image_daily_limit',
            field=models.IntegerField(default=0, help_text='Daily AI image generation limit (DALL-E).'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_plan_daily_limit',
            field=models.IntegerField(default=0, help_text='Daily AI plan/analysis operations limit.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_voice_daily_limit',
            field=models.IntegerField(default=0, help_text='Daily voice transcription limit.'),
        ),
    ]
