# Generated by Django 5.2.11 on 2026-02-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_stripewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Plan the user is downgrading to (takes effect at period end)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='pending_plan_effective_date',
            field=models.DateTimeField(blank=True, help_text='When the pending plan change takes effect', null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, default='', help_text='Stripe SubscriptionSchedule ID for pending downgrades', max_length=255),
        ),
    ]
