# Generated by Django 5.2.11 on 2026-03-08 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_allow_blank_stripe_subscription_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('referral_code', models.CharField(db_index=True, help_text='The code used for this referral', max_length=50)),
                ('referred_has_paid', models.BooleanField(default=False, help_text='Whether the referred user has subscribed to a paid plan')),
                ('reward_granted', models.BooleanField(default=False, help_text='Whether a free month was granted for this batch of 3')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the referred user first subscribed to a paid plan', null=True)),
                ('referred', models.OneToOneField(help_text='User who signed up via the referral', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(help_text='User who shared the referral link', on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'referrals',
                'ordering': ['-created_at'],
            },
        ),
    ]
