# Generated by Django 5.2.11 on 2026-03-11 02:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_add_has_public_dreams"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this promotion", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Public-facing description shown to users",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        help_text="When the promotion becomes available"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(help_text="When the promotion expires"),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        help_text="How long the discount lasts after redemption (in days)"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                        ],
                        help_text="Whether the discount is a percentage or fixed dollar amount",
                        max_length=20,
                    ),
                ),
                (
                    "max_redemptions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total redemptions. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                (
                    "condition_type",
                    models.CharField(
                        choices=[
                            ("none", "None (everyone)"),
                            ("email_endswith", "Email Ends With"),
                        ],
                        default="none",
                        help_text="Eligibility condition type",
                        max_length=30,
                    ),
                ),
                (
                    "condition_value",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Condition value (e.g. '@school.ca' for email_endswith)",
                        max_length=100,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[("all", "All Users"), ("new_users", "New Users Only")],
                        default="all",
                        help_text="Who can see and redeem this promotion",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Admin toggle to enable/disable the promotion",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "promotions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="promotions_is_acti_dbec31_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromotionPlanDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed dollar amount, per promotion.discount_type",
                        max_digits=8,
                    ),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Auto-created Stripe coupon ID (do not edit manually)",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_discounts",
                        to="subscriptions.subscriptionplan",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_discounts",
                        to="subscriptions.promotion",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_plan_discounts",
                "unique_together": {("promotion", "plan")},
            },
        ),
        migrations.CreateModel(
            name="PromotionRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_coupon_id",
                    models.CharField(
                        help_text="The Stripe coupon ID used for this redemption",
                        max_length=255,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="subscriptions.promotion",
                    ),
                ),
                (
                    "promotion_plan_discount",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="subscriptions.promotionplandiscount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "promotion_redemptions",
                "indexes": [
                    models.Index(
                        fields=["promotion", "user"],
                        name="promotion_r_promoti_df7ca3_idx",
                    )
                ],
                "unique_together": {("promotion", "user")},
            },
        ),
    ]
