# Generated by Django 5.1.15 on 2026-03-15 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_promotionchangelog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique referral code (DP-REF-XXXXXXXX)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "uses_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this code has been used"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "referral_codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reward_type",
                    models.CharField(
                        choices=[
                            ("xp", "XP Bonus"),
                            ("premium_days", "Premium Days"),
                            ("cosmetic", "Cosmetic Reward"),
                            ("discount", "Lifetime Discount"),
                        ],
                        help_text="Type of reward granted",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default=0,
                        help_text="Amount: XP points, premium days, discount %, or 1 for cosmetic",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable reward description",
                        max_length=200,
                    ),
                ),
                (
                    "tier_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Tier that unlocked this reward (bronze/silver/gold/diamond)",
                        max_length=20,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "referral_rewards",
                "ordering": ["-claimed_at"],
            },
        ),
        migrations.AddField(
            model_name="referral",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the referral was completed (referred user active 7+ days)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("rewarded", "Rewarded"),
                ],
                db_index=True,
                default="pending",
                help_text="pending -> completed (onboarding done) -> rewarded (rewards given)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="referral",
            name="reward_granted",
            field=models.BooleanField(
                default=False,
                help_text="Whether rewards have been granted for this referral",
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(
                fields=["referrer", "status"], name="referrals_referre_cefb5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="referral",
            index=models.Index(fields=["status"], name="referrals_status_135a0e_idx"),
        ),
        migrations.AddField(
            model_name="referralcode",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_code_obj",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="referral",
            field=models.ForeignKey(
                blank=True,
                help_text="The referral that triggered this reward (null for tier milestones)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rewards",
                to="subscriptions.referral",
            ),
        ),
        migrations.AddField(
            model_name="referralreward",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referral_rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
