# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        ("dreams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="dreams.dream",
            ),
        ),
    ]
