# Generated by Django 5.0.1 on 2026-02-05 02:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StripeCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe customer ID (cus_xxxxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "stripe_customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        db_index=True,
                        help_text="Stripe Subscription ID (sub_xxxxx)",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                            ("trialing", "Trialing"),
                            ("unpaid", "Unpaid"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="incomplete",
                        max_length=30,
                    ),
                ),
                (
                    "current_period_start",
                    models.DateTimeField(
                        blank=True,
                        help_text="Start of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "current_period_end",
                    models.DateTimeField(
                        blank=True,
                        help_text="End of the current billing period",
                        null=True,
                    ),
                ),
                (
                    "cancel_at_period_end",
                    models.BooleanField(
                        default=False,
                        help_text="If True, subscription cancels at end of current period",
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user requested cancellation",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Plan display name (Free, Premium, Pro)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe plan identifier (free, premium, pro)",
                        unique=True,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Price ID (price_xxxxx). Empty for free tier.",
                        max_length=255,
                    ),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Monthly price in USD",
                        max_digits=6,
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON object describing plan features for display",
                    ),
                ),
                (
                    "dream_limit",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum active dreams allowed. -1 for unlimited.",
                    ),
                ),
                (
                    "has_ai",
                    models.BooleanField(
                        default=False, help_text="Access to AI coaching features"
                    ),
                ),
                (
                    "has_buddy",
                    models.BooleanField(
                        default=False, help_text="Access to Dream Buddy matching"
                    ),
                ),
                (
                    "has_circles",
                    models.BooleanField(
                        default=False,
                        help_text="Access to Dream Circles (group accountability)",
                    ),
                ),
                (
                    "has_vision_board",
                    models.BooleanField(
                        default=False, help_text="Access to AI Vision Board generation"
                    ),
                ),
                (
                    "has_league",
                    models.BooleanField(
                        default=False, help_text="Access to competitive leagues"
                    ),
                ),
                (
                    "has_ads",
                    models.BooleanField(
                        default=True,
                        help_text="Whether ads are shown to users on this plan",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is currently available for purchase",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["price_monthly"],
            },
        ),
    ]
