# Generated by Django 5.0.14 on 2026-03-26 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dp_auth", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "login_method",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("google", "Google"),
                            ("apple", "Apple"),
                            ("2fa", "Two-Factor"),
                        ],
                        default="password",
                        max_length=30,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dp_auth_login_event",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="dp_auth_log_user_id_3d1251_idx",
                    ),
                    models.Index(
                        fields=["ip_address"], name="dp_auth_log_ip_addr_c59d4b_idx"
                    ),
                ],
            },
        ),
    ]
