# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
import django.utils.timezone
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "display_name",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                (
                    "avatar_url",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                (
                    "avatar_image",
                    models.ImageField(
                        blank=True,
                        help_text="Uploaded avatar image file.",
                        upload_to="avatars/",
                    ),
                ),
                (
                    "bio",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Short user biography (encrypted at rest).",
                    ),
                ),
                (
                    "location",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="User location (encrypted at rest).",
                    ),
                ),
                (
                    "social_links",
                    models.JSONField(
                        blank=True,
                        help_text='Social media links: {twitter: "", instagram: "", ...}',
                        null=True,
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("friends", "Friends Only"),
                            ("private", "Private"),
                        ],
                        default="public",
                        help_text="Who can see this profile.",
                        max_length=20,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Paris", max_length=50)),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[
                            ("auto", "Auto"),
                            ("dark", "Dark"),
                            ("light", "Light"),
                        ],
                        default="auto",
                        help_text="Preferred theme mode: auto, dark, or light.",
                        max_length=10,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#8B5CF6",
                        help_text="User accent/brand color hex code (e.g. #8B5CF6).",
                        max_length=20,
                    ),
                ),
                (
                    "subscription",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                ("subscription_ends", models.DateTimeField(blank=True, null=True)),
                (
                    "work_schedule",
                    models.JSONField(
                        blank=True,
                        help_text='Work schedule: {workDays: [], startTime: "", endTime: ""}',
                        null=True,
                    ),
                ),
                (
                    "notification_prefs",
                    models.JSONField(
                        blank=True, help_text="Notification preferences", null=True
                    ),
                ),
                (
                    "app_prefs",
                    models.JSONField(
                        blank=True,
                        help_text='App preferences: {theme: "", language: ""}',
                        null=True,
                    ),
                ),
                (
                    "persona",
                    models.JSONField(
                        blank=True,
                        help_text="User persona for AI calibration: {available_hours_per_week, preferred_schedule, budget_range, fitness_level, learning_style, typical_day, occupation, astrological_sign, global_motivation, global_constraints}",
                        null=True,
                    ),
                ),
                (
                    "calendar_preferences",
                    models.JSONField(
                        blank=True,
                        help_text="Calendar preferences: {buffer_minutes: 0-60, min_event_duration: 15-120}",
                        null=True,
                    ),
                ),
                (
                    "energy_profile",
                    models.JSONField(
                        blank=True,
                        help_text='Energy profile for smart scheduling: {"peak_hours": [{"start": 9, "end": 12}], "low_energy_hours": [{"start": 13, "end": 14}], "energy_pattern": "morning_person"|"night_owl"|"steady"}',
                        null=True,
                    ),
                ),
                (
                    "notification_timing",
                    models.JSONField(
                        blank=True,
                        help_text='AI-optimized notification timing preferences: {"optimal_times": [{"notification_type": "reminder", "best_hour": 9, "best_day": "weekday", "reason": "..."}], "quiet_hours": {"start": 22, "end": 7}, "engagement_score": 0.85, "last_optimized": "2026-03-01T12:00:00Z"}',
                        null=True,
                    ),
                ),
                ("xp", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("streak_days", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("streak_updated_at", models.DateField(blank=True, null=True)),
                (
                    "streak_freeze_used_at",
                    models.DateField(
                        blank=True,
                        help_text="Last date a streak freeze was used (max 1 per week).",
                        null=True,
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_online", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("totp_enabled", models.BooleanField(default=False)),
                (
                    "totp_secret",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "backup_codes",
                    models.JSONField(
                        blank=True, help_text="Hashed 2FA backup codes", null=True
                    ),
                ),
                ("onboarding_completed", models.BooleanField(default=False)),
                (
                    "dreamer_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visionary", "Visionary"),
                            ("achiever", "Achiever"),
                            ("explorer", "Explorer"),
                            ("collaborator", "Collaborator"),
                            ("strategist", "Strategist"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the account was deactivated. Hard-delete scheduled 30 days after.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("new_email", models.EmailField(max_length=254)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_change_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["subscription"], name="users_subscri_f90c0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_activity"], name="users_last_ac_a9fd4f_idx"
            ),
        ),
    ]
