# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_firebase_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_image",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded avatar image file.",
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(
                blank=True, default="", help_text="Short user biography."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User location (city, country).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("friends", "Friends Only"),
                    ("private", "Private"),
                ],
                default="public",
                help_text="Who can see this profile.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_links",
            field=models.JSONField(
                blank=True,
                help_text='Social media links: {twitter: "", instagram: "", ...}',
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EmailChangeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("new_email", models.EmailField(max_length=254)),
                ("token", models.CharField(db_index=True, max_length=128, unique=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_change_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="DreamBuddy",
        ),
    ]
