# Generated by Django 5.2.6 on 2026-02-22 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_avatar_image_user_bio_user_location_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FcmToken",
        ),
    ]
