# Generated by Django 5.0.6 on 2026-02-22 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_fcmtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji or icon identifier', max_length=50)),
                ('category', models.CharField(choices=[('streaks', 'Streaks'), ('dreams', 'Dreams'), ('social', 'Social'), ('tasks', 'Tasks'), ('special', 'Special')], db_index=True, max_length=20)),
                ('xp_reward', models.IntegerField(default=0)),
                ('condition_type', models.CharField(choices=[('streak_days', 'Streak Days'), ('dreams_created', 'Dreams Created'), ('dreams_completed', 'Dreams Completed'), ('tasks_completed', 'Tasks Completed'), ('friends_count', 'Friends Count'), ('circles_joined', 'Circles Joined'), ('level_reached', 'Level Reached'), ('xp_earned', 'XP Earned'), ('early_task', 'Early Task (before 8am)'), ('late_task', 'Late Task (after 10pm)'), ('first_dream', 'First Dream Created'), ('first_buddy', 'First Buddy Matched'), ('vision_created', 'Vision Board Created')], max_length=30)),
                ('condition_value', models.IntegerField(default=1, help_text='Threshold value to unlock')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['category', 'condition_value'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('tasks_completed', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('minutes_active', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'daily_activities',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_activ_user_id_cd76b0_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='users.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
