# Generated by Django 5.0.6 on 2026-02-22 23:47

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_achievement_user_is_online_user_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Short user biography (encrypted at rest).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='User location (encrypted at rest).'),
        ),
    ]
