# Generated by Django 5.2.11 on 2026-02-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_backup_codes_user_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyactivity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='dailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_daily_activity'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'achievement'), name='unique_user_achievement'),
        ),
    ]
