# Generated by Django 5.2.11 on 2026-03-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], db_index=True, default='common', help_text='Rarity tier that determines badge glow color.', max_length=20),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Current progress towards the achievement requirement value.'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('streaks', 'Streaks'), ('dreams', 'Dreams'), ('social', 'Social'), ('tasks', 'Tasks'), ('special', 'Special'), ('profile', 'Profile')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='condition_type',
            field=models.CharField(choices=[('streak_days', 'Streak Days'), ('dreams_created', 'Dreams Created'), ('dreams_completed', 'Dreams Completed'), ('tasks_completed', 'Tasks Completed'), ('friends_count', 'Friends Count'), ('circles_joined', 'Circles Joined'), ('level_reached', 'Level Reached'), ('xp_earned', 'XP Earned'), ('early_task', 'Early Task (before 8am)'), ('late_task', 'Late Task (after 10pm)'), ('first_dream', 'First Dream Created'), ('first_buddy', 'First Buddy Matched'), ('vision_created', 'Vision Board Created'), ('posts_created', 'Posts Created'), ('likes_received', 'Likes Received'), ('profile_completed', 'Profile Completed')], max_length=30),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='icon',
            field=models.CharField(help_text='Lucide icon name (e.g. sparkles, flame, trophy)', max_length=50),
        ),
    ]
