# Generated by Django 5.2.11 on 2026-03-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_seed_achievement_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accent_color',
            field=models.CharField(default='#8B5CF6', help_text='User accent/brand color hex code (e.g. #8B5CF6).', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_mode',
            field=models.CharField(choices=[('auto', 'Auto'), ('dark', 'Dark'), ('light', 'Light')], default='auto', help_text='Preferred theme mode: auto, dark, or light.', max_length=10),
        ),
    ]
