# Generated by Django 5.2.11 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_theme_mode_accent_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(
                blank=True,
                null=True,
                help_text='When the account was deactivated. Hard-delete scheduled 30 days after.',
            ),
        ),
    ]
