# Generated by Django 5.2.11 on 2026-03-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_deactivated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dreamer_type',
            field=models.CharField(blank=True, choices=[('visionary', 'Visionary'), ('achiever', 'Achiever'), ('explorer', 'Explorer'), ('collaborator', 'Collaborator'), ('strategist', 'Strategist')], max_length=30),
        ),
    ]
