# Generated by Django 5.2.11 on 2026-03-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_persona_and_language'),
        ('users', '0017_user_notification_timing'),
    ]

    operations = [
    ]
