# Generated by Django 5.1.15 on 2026-03-15 04:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0023_goal_refinement_session"),
        ("users", "0018_merge_20260310_0205"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="longest_streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_freeze_used_at",
            field=models.DateField(
                blank=True,
                help_text="Last date a streak freeze was used (max 1 per week).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="streak_updated_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HabitChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "chain_type",
                    models.CharField(
                        choices=[
                            ("check_in", "Check-in"),
                            ("task_completion", "Task Completion"),
                            ("focus_timer", "Focus Timer"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habit_chains",
                        to="dreams.dream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habit_chains",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "habit_chains",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="habit_chain_user_id_52d2a5_idx"
                    ),
                    models.Index(
                        fields=["user", "chain_type", "-date"],
                        name="habit_chain_user_id_862b5f_idx",
                    ),
                ],
            },
        ),
    ]
