# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the category.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the category.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the category shown to users.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Icon identifier or URL for the category.",
                        max_length=255,
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in which the category appears in the store.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the category is visible in the store.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Category",
                "verbose_name_plural": "Store Categories",
                "db_table": "store_categories",
                "ordering": ["display_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="store_categ_slug_7ee8fd_idx"),
                    models.Index(
                        fields=["is_active", "display_order"],
                        name="store_categ_is_acti_0ac8c6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoreItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the store item.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the item.", max_length=200
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly slug for the item.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Description of the item shown to users.",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL to the item preview image.",
                        max_length=500,
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe Price ID for one-time payment processing.",
                        max_length=255,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the item in USD.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("badge_frame", "Badge Frame"),
                            ("theme_skin", "Theme Skin"),
                            ("avatar_decoration", "Avatar Decoration"),
                            ("chat_bubble", "Chat Bubble"),
                            ("streak_shield", "Streak Shield"),
                            ("xp_booster", "XP Booster"),
                        ],
                        db_index=True,
                        help_text="Type of cosmetic item.",
                        max_length=30,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        db_index=True,
                        default="common",
                        help_text="Rarity tier of the item affecting visual presentation.",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional item metadata (e.g., colors, animation settings, duration).",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the item is available for purchase.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the item was added to the store.",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Category this item belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="store.storecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Item",
                "verbose_name_plural": "Store Items",
                "db_table": "store_items",
                "ordering": ["category", "price"],
            },
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this inventory entry.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the item was purchased.",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent ID for the purchase transaction.",
                        max_length=255,
                    ),
                ),
                (
                    "is_equipped",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the item is currently equipped/active for the user.",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The store item that was purchased.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owners",
                        to="store.storeitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Inventory",
                "verbose_name_plural": "User Inventories",
                "db_table": "user_inventory",
                "ordering": ["-purchased_at"],
            },
        ),
    ]
