# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="storeitem",
            name="available_from",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of availability window (null = always available).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="available_until",
            field=models.DateTimeField(
                blank=True,
                help_text="End of availability window (null = always available).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storeitem",
            name="xp_price",
            field=models.IntegerField(
                default=0,
                help_text="Price in XP for XP-based purchasing (0 = not purchasable with XP).",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="User-provided reason for the refund."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_refund_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("admin_notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inventory_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="store.userinventory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_refund_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional personal message from the sender.",
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Stripe PaymentIntent ID for the gift purchase.",
                        max_length=255,
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        help_text="The gifted store item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts",
                        to="store.storeitem",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives the gift.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the gift.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gifts_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_gifts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_claimed"],
                        name="store_gifts_recipie_0f7d42_idx",
                    ),
                    models.Index(
                        fields=["sender"], name="store_gifts_sender__3d18a6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="store.storeitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_wishlist",
                "ordering": ["-created_at"],
                "unique_together": {("user", "item")},
            },
        ),
    ]
