# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Planned duration in minutes"
                    ),
                ),
                (
                    "actual_minutes",
                    models.PositiveIntegerField(
                        default=0, help_text="Actual time focused in minutes"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[("work", "Work"), ("break", "Break")],
                        default="work",
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "focus_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                ("order", models.IntegerField()),
                ("estimated_minutes", models.IntegerField(blank=True, null=True)),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="Ideal/soft date to complete this goal (no penalty if missed)",
                        null=True,
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="Hard deadline -- must be done by this date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("reminder_enabled", models.BooleanField(default=True)),
                ("reminder_time", models.DateTimeField(blank=True, null=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "goals",
                "ordering": ["dream", "milestone__order", "order"],
            },
        ),
        migrations.CreateModel(
            name="Obstacle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                ("description", encrypted_model_fields.fields.EncryptedTextField()),
                (
                    "obstacle_type",
                    models.CharField(
                        choices=[("predicted", "Predicted"), ("actual", "Actual")],
                        default="predicted",
                        max_length=20,
                    ),
                ),
                (
                    "solution",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("ignored", "Ignored"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "obstacles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("conversation", models.UUIDField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("questionnaire_generating", "Generating Questionnaire"),
                            ("awaiting_user", "Awaiting User Response"),
                            ("ai_processing", "AI Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("schedule", "Scheduled"),
                            ("manual", "Manual"),
                            ("auto_expire", "Auto Expired"),
                        ],
                        default="schedule",
                        max_length=20,
                    ),
                ),
                (
                    "questionnaire",
                    models.JSONField(
                        blank=True,
                        help_text="AI-generated questions: [{id, question_type, question, options, ...}]",
                        null=True,
                    ),
                ),
                (
                    "user_responses",
                    models.JSONField(
                        blank=True,
                        help_text="User answers: {question_id: answer_value}",
                        null=True,
                    ),
                ),
                (
                    "questionnaire_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="After this time, check-in runs autonomously if user has not responded",
                        null=True,
                    ),
                ),
                (
                    "pace_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("significantly_behind", "Significantly Behind"),
                            ("behind", "Behind"),
                            ("on_track", "On Track"),
                            ("ahead", "Ahead"),
                            ("significantly_ahead", "Significantly Ahead"),
                        ],
                        default="",
                        max_length=25,
                    ),
                ),
                ("next_checkin_interval_days", models.IntegerField(default=14)),
                ("progress_at_checkin", models.FloatField(default=0.0)),
                ("tasks_completed_since_last", models.IntegerField(default=0)),
                ("tasks_overdue_at_checkin", models.IntegerField(default=0)),
                ("ai_actions", models.JSONField(default=list)),
                ("tasks_created", models.IntegerField(default=0)),
                ("milestones_adjusted", models.IntegerField(default=0)),
                ("months_generated_through", models.IntegerField(default=0)),
                ("coaching_message", models.TextField(blank=True)),
                ("adjustment_summary", models.TextField(blank=True)),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "plan_checkins",
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "scheduled_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "scheduled_time",
                    models.CharField(
                        blank=True, help_text="HH:MM format", max_length=5
                    ),
                ),
                ("duration_mins", models.IntegerField(blank=True, null=True)),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="Ideal/soft date to do this task (no penalty if missed)",
                        null=True,
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="Hard deadline -- must be done by this date",
                        null=True,
                    ),
                ),
                (
                    "recurrence",
                    models.JSONField(
                        blank=True,
                        help_text='Recurrence pattern: {type: "daily|weekly|monthly", interval: 1, ...}',
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_two_minute_start", models.BooleanField(default=False)),
                (
                    "chain_next_delay_days",
                    models.IntegerField(
                        blank=True,
                        help_text="Days after completion to schedule the next task in the chain",
                        null=True,
                    ),
                ),
                (
                    "chain_template_title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Custom title for the next task in the chain (uses current title if blank)",
                        max_length=255,
                    ),
                ),
                (
                    "is_chain",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this task is part of a recurring chain",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tasks",
                "ordering": ["goal", "scheduled_date", "order"],
            },
        ),
        migrations.CreateModel(
            name="CalibrationResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question",
                    models.TextField(help_text="AI-generated calibration question"),
                ),
                (
                    "answer",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="User response to the question (encrypted at rest)",
                    ),
                ),
                (
                    "question_number",
                    models.IntegerField(
                        help_text="Order of question in the calibration flow"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Question category: experience, timeline, resources, motivation, constraints, specifics, lifestyle, preferences",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calibration_responses",
                        to="dreams.dream",
                    ),
                ),
            ],
            options={
                "db_table": "calibration_responses",
                "ordering": ["dream", "question_number"],
            },
        ),
        migrations.CreateModel(
            name="DreamMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        help_text="Order within the dream (1 = first milestone)"
                    ),
                ),
                (
                    "target_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date by which this milestone should be achieved",
                        null=True,
                    ),
                ),
                (
                    "expected_date",
                    models.DateField(
                        blank=True,
                        help_text="Ideal/soft date to complete this milestone (no penalty if missed)",
                        null=True,
                    ),
                ),
                (
                    "deadline_date",
                    models.DateField(
                        blank=True,
                        help_text="Hard deadline -- must be done by this date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("has_tasks", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="dreams.dream",
                    ),
                ),
            ],
            options={
                "db_table": "milestones",
                "ordering": ["dream", "order"],
            },
        ),
        migrations.CreateModel(
            name="DreamProgressSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("progress_percentage", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_snapshots",
                        to="dreams.dream",
                    ),
                ),
            ],
            options={
                "db_table": "dream_progress_snapshots",
                "ordering": ["-date"],
            },
        ),
    ]
