# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0002_initial"),
        ("plans", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="focussession",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="focus_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="The milestone this goal belongs to (null for legacy goals without milestones)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="plans.dreammilestone",
            ),
        ),
        migrations.AddField(
            model_name="obstacle",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="obstacle",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                help_text="The goal this obstacle is linked to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="plans.goal",
            ),
        ),
        migrations.AddField(
            model_name="obstacle",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="The milestone this obstacle is linked to (optional)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="plans.dreammilestone",
            ),
        ),
        migrations.AddField(
            model_name="plancheckin",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checkins",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="chain_parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The previous task in this chain",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chain_children",
                to="plans.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="plans.goal",
            ),
        ),
        migrations.AddField(
            model_name="focussession",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="focus_sessions",
                to="plans.task",
            ),
        ),
        migrations.AddIndex(
            model_name="calibrationresponse",
            index=models.Index(
                fields=["dream", "question_number"],
                name="calibration_dream_i_995ace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(
                fields=["dream", "order"], name="milestones_dream_i_4a2f78_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(fields=["status"], name="milestones_status_2abe2f_idx"),
        ),
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(
                fields=["target_date"], name="milestones_target__3769ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(
                fields=["expected_date"], name="milestones_expecte_47e9cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dreammilestone",
            index=models.Index(
                fields=["deadline_date"], name="milestones_deadlin_151c63_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dreamprogresssnapshot",
            index=models.Index(
                fields=["dream", "-date"], name="dream_progr_dream_i_6974d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dreamprogresssnapshot",
            constraint=models.UniqueConstraint(
                fields=("dream", "date"), name="unique_dream_progress_date"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["dream", "order"], name="goals_dream_i_18d7f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["status"], name="goals_status_6bb941_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["scheduled_start"], name="goals_schedul_a281e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["milestone", "order"], name="goals_milesto_67ee09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["expected_date"], name="goals_expecte_1bcf5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["deadline_date"], name="goals_deadlin_5df156_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="obstacle",
            index=models.Index(
                fields=["milestone"], name="obstacles_milesto_961843_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="obstacle",
            index=models.Index(fields=["goal"], name="obstacles_goal_id_319a13_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["goal", "scheduled_date"], name="tasks_goal_id_686a81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["scheduled_date"], name="tasks_schedul_49269d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["status", "-created_at"], name="tasks_status_ec5702_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["expected_date"], name="tasks_expecte_e0f58c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["deadline_date"], name="tasks_deadlin_68dd57_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["chain_parent"], name="tasks_chain_p_306c93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="focussession",
            index=models.Index(
                fields=["user", "-started_at"], name="focus_sessi_user_id_ba172e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="focussession",
            index=models.Index(
                fields=["user", "completed"], name="focus_sessi_user_id_1027c7_idx"
            ),
        ),
    ]
