# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RankSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(help_text="Rank at the time of snapshot."),
                ),
                (
                    "xp",
                    models.IntegerField(
                        help_text="XP earned this season at the time of snapshot."
                    ),
                ),
                (
                    "snapshot_date",
                    models.DateField(db_index=True, help_text="Date of this snapshot."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "rank_snapshots",
                "ordering": ["-snapshot_date"],
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this season.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name of the season (e.g., "Season 1 - Winter 2026").',
                        max_length=200,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When this season starts."),
                ),
                ("end_date", models.DateTimeField(help_text="When this season ends.")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this season is currently active. Only one season should be active at a time.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("processing", "Processing"),
                            ("ended", "Ended"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Lifecycle status of the season.",
                        max_length=20,
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the season in days (stored at creation time).",
                        null=True,
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of rewards available for this season (varies by league achieved).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "db_table": "seasons",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SeasonConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "season_duration_days",
                    models.PositiveIntegerField(
                        default=180,
                        help_text="Default duration in days for new seasons.",
                    ),
                ),
                (
                    "group_target_size",
                    models.PositiveIntegerField(
                        default=20, help_text="Target number of members per group."
                    ),
                ),
                (
                    "group_max_size",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Maximum number of members allowed per group.",
                    ),
                ),
                (
                    "group_min_size",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minimum number of members to keep a group active.",
                    ),
                ),
                (
                    "promotion_xp_threshold",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="XP earned this season to be eligible for promotion.",
                    ),
                ),
                (
                    "relegation_xp_threshold",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="XP below this threshold triggers relegation risk.",
                    ),
                ),
                (
                    "auto_create_next_season",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically create the next season when one ends.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Season Config",
                "verbose_name_plural": "Season Config",
                "db_table": "season_config",
            },
        ),
        migrations.CreateModel(
            name="SeasonParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this participant record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "xp_earned",
                    models.PositiveIntegerField(
                        default=0, help_text="Total XP earned during this season."
                    ),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Final rank in the season (computed from XP).",
                        null=True,
                    ),
                ),
                (
                    "rewards_claimed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has claimed their end-of-season rewards.",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the user joined this season."
                    ),
                ),
            ],
            options={
                "verbose_name": "Season Participant",
                "verbose_name_plural": "Season Participants",
                "db_table": "season_participants",
                "ordering": ["-xp_earned"],
            },
        ),
        migrations.CreateModel(
            name="SeasonReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this reward record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rewards_claimed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has claimed their rewards.",
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the rewards were claimed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Season Reward",
                "verbose_name_plural": "Season Rewards",
                "db_table": "season_rewards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this league.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name of the league (e.g., "Bronze League").',
                        max_length=100,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                            ("diamond", "Diamond"),
                            ("master", "Master"),
                            ("legend", "Legend"),
                        ],
                        db_index=True,
                        help_text="The tier level of this league.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "min_xp",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum XP required to enter this league.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_xp",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum XP for this league. Null for the top league (Legend).",
                        null=True,
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the league icon/badge image.",
                        max_length=500,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text='Hex color code for the league (e.g., "#CD7F32" for Bronze).',
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the league and what it represents.",
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of rewards for reaching this league (e.g., badges, titles).",
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "db_table": "leagues",
                "ordering": ["min_xp"],
                "indexes": [
                    models.Index(
                        fields=["min_xp", "max_xp"], name="idx_league_xp_range"
                    ),
                    models.Index(fields=["tier"], name="idx_league_tier"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeagueGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_number",
                    models.PositiveIntegerField(
                        help_text="Group number within this season+league (1-indexed)."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this group is active (False after season ends or rebalance empties it).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "league",
                    models.ForeignKey(
                        help_text="The league tier this group is in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Group",
                "verbose_name_plural": "League Groups",
                "db_table": "league_groups",
                "ordering": ["season", "league", "group_number"],
            },
        ),
        migrations.CreateModel(
            name="LeagueGroupMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the user was assigned to this group.",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="The group this membership belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="leagues.leaguegroup",
                    ),
                ),
                (
                    "promoted_from_group",
                    models.ForeignKey(
                        blank=True,
                        help_text="The group the user was promoted from, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promotions_out",
                        to="leagues.leaguegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Group Membership",
                "verbose_name_plural": "League Group Memberships",
                "db_table": "league_group_memberships",
            },
        ),
        migrations.CreateModel(
            name="LeagueSeason",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this league season.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name of the season (e.g., "Season of Growth - Spring 2026").',
                        max_length=200,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("growth", "Growth"),
                            ("fire", "Fire"),
                            ("ocean", "Ocean"),
                            ("cosmic", "Cosmic"),
                            ("aurora", "Aurora"),
                            ("crystal", "Crystal"),
                            ("storm", "Storm"),
                            ("bloom", "Bloom"),
                        ],
                        default="growth",
                        help_text="Visual theme for the season (growth, fire, ocean, cosmic, etc.).",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the season theme and what makes it special.",
                    ),
                ),
                ("start_date", models.DateField(help_text="When this season starts.")),
                ("end_date", models.DateField(help_text="When this season ends.")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this season is currently active. Only one should be active at a time.",
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Tiered reward definitions. Each entry: {"rank_min": 1, "rank_max": 3, "reward_type": "badge", "reward_id": "gold_crown", "title": "Gold Crown Badge"}.',
                    ),
                ),
                (
                    "theme_colors",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Theme color palette: {"primary": "#hex", "secondary": "#hex", "accent": "#hex"}.',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "League Season",
                "verbose_name_plural": "League Seasons",
                "db_table": "league_seasons",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(fields=["is_active"], name="idx_lseason_active"),
                    models.Index(
                        fields=["start_date", "end_date"], name="idx_lseason_dates"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeagueStanding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this standing record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Current rank within the league for this season (1 = top).",
                    ),
                ),
                (
                    "xp_earned_this_season",
                    models.IntegerField(
                        default=0,
                        help_text="Total XP earned during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tasks_completed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of tasks completed during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dreams_completed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of dreams completed during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "streak_best",
                    models.IntegerField(
                        default=0,
                        help_text="Best streak (consecutive days) during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        help_text="The league this user is currently in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Standing",
                "verbose_name_plural": "League Standings",
                "db_table": "league_standings",
                "ordering": ["rank"],
            },
        ),
    ]
