# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this season.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name of the season (e.g., "Season 1 - Winter 2026").',
                        max_length=200,
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(help_text="When this season starts."),
                ),
                ("end_date", models.DateTimeField(help_text="When this season ends.")),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this season is currently active. Only one season should be active at a time.",
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of rewards available for this season (varies by league achieved).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "db_table": "seasons",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SeasonReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this reward record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rewards_claimed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has claimed their rewards.",
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the rewards were claimed.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Season Reward",
                "verbose_name_plural": "Season Rewards",
                "db_table": "season_rewards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this league.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Display name of the league (e.g., "Bronze League").',
                        max_length=100,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("bronze", "Bronze"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                            ("diamond", "Diamond"),
                            ("master", "Master"),
                            ("legend", "Legend"),
                        ],
                        db_index=True,
                        help_text="The tier level of this league.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "min_xp",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum XP required to enter this league.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "max_xp",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum XP for this league. Null for the top league (Legend).",
                        null=True,
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the league icon/badge image.",
                        max_length=500,
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        blank=True,
                        help_text='Hex color code for the league (e.g., "#CD7F32" for Bronze).',
                        max_length=7,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the league and what it represents.",
                    ),
                ),
                (
                    "rewards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of rewards for reaching this league (e.g., badges, titles).",
                    ),
                ),
            ],
            options={
                "verbose_name": "League",
                "verbose_name_plural": "Leagues",
                "db_table": "leagues",
                "ordering": ["min_xp"],
                "indexes": [
                    models.Index(
                        fields=["min_xp", "max_xp"], name="idx_league_xp_range"
                    ),
                    models.Index(fields=["tier"], name="idx_league_tier"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeagueStanding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this standing record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        db_index=True,
                        default=0,
                        help_text="Current rank within the league for this season (1 = top).",
                    ),
                ),
                (
                    "xp_earned_this_season",
                    models.IntegerField(
                        default=0,
                        help_text="Total XP earned during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tasks_completed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of tasks completed during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dreams_completed",
                    models.IntegerField(
                        default=0,
                        help_text="Number of dreams completed during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "streak_best",
                    models.IntegerField(
                        default=0,
                        help_text="Best streak (consecutive days) during this season.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        help_text="The league this user is currently in.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="leagues.league",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Standing",
                "verbose_name_plural": "League Standings",
                "db_table": "league_standings",
                "ordering": ["rank"],
            },
        ),
    ]
