# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguestanding",
            name="user",
            field=models.ForeignKey(
                help_text="The user this standing belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_standings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaguegroupmembership",
            name="standing",
            field=models.OneToOneField(
                help_text="The league standing this membership is for.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_membership",
                to="leagues.leaguestanding",
            ),
        ),
        migrations.AddField(
            model_name="ranksnapshot",
            name="league",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_snapshots",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="ranksnapshot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_snapshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(fields=["is_active"], name="idx_season_active"),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_season_dates"
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(fields=["status"], name="idx_season_status"),
        ),
        migrations.AddField(
            model_name="ranksnapshot",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rank_snapshots",
                to="leagues.season",
            ),
        ),
        migrations.AddField(
            model_name="leaguestanding",
            name="season",
            field=models.ForeignKey(
                help_text="The season this standing applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to="leagues.season",
            ),
        ),
        migrations.AddField(
            model_name="leaguegroup",
            name="season",
            field=models.ForeignKey(
                help_text="The season this group belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="groups",
                to="leagues.season",
            ),
        ),
        migrations.AddField(
            model_name="seasonparticipant",
            name="season",
            field=models.ForeignKey(
                help_text="The league season this participation belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="leagues.leagueseason",
            ),
        ),
        migrations.AddField(
            model_name="seasonparticipant",
            name="user",
            field=models.ForeignKey(
                help_text="The user participating in the season.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seasonreward",
            name="league_achieved",
            field=models.ForeignKey(
                help_text="The league the user was in when the season ended.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rewards",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="seasonreward",
            name="season",
            field=models.ForeignKey(
                help_text="The season this reward is from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rewards",
                to="leagues.season",
            ),
        ),
        migrations.AddField(
            model_name="seasonreward",
            name="user",
            field=models.ForeignKey(
                help_text="The user who earned this reward.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leaguegroupmembership",
            index=models.Index(fields=["group"], name="idx_lgm_group"),
        ),
        migrations.AddIndex(
            model_name="ranksnapshot",
            index=models.Index(
                fields=["user", "season", "-snapshot_date"],
                name="idx_snapshot_user_season_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="ranksnapshot",
            constraint=models.UniqueConstraint(
                fields=("user", "season", "snapshot_date"), name="unique_rank_snapshot"
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["season", "rank"], name="idx_standing_season_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["season", "league", "-xp_earned_this_season"],
                name="idx_standing_league_xp",
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["season", "-xp_earned_this_season"],
                name="idx_standing_season_xp",
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["user", "season"], name="idx_standing_user_season"
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["league", "rank"], name="idx_standing_league_rank"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaguestanding",
            constraint=models.UniqueConstraint(
                fields=("user", "season"), name="unique_league_standing"
            ),
        ),
        migrations.AddIndex(
            model_name="leaguegroup",
            index=models.Index(
                fields=["season", "league", "is_active"],
                name="idx_lg_season_league_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaguegroup",
            constraint=models.UniqueConstraint(
                fields=("season", "league", "group_number"), name="unique_league_group"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonparticipant",
            index=models.Index(
                fields=["season", "-xp_earned"], name="idx_sparticipant_season_xp"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonparticipant",
            index=models.Index(
                fields=["season", "rank"], name="idx_sparticipant_season_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonparticipant",
            index=models.Index(
                fields=["user", "season"], name="idx_sparticipant_user_season"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seasonparticipant",
            unique_together={("season", "user")},
        ),
        migrations.AddIndex(
            model_name="seasonreward",
            index=models.Index(
                fields=["user", "rewards_claimed"], name="idx_reward_user_claimed"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonreward",
            index=models.Index(
                fields=["season", "league_achieved"], name="idx_reward_season_league"
            ),
        ),
        migrations.AddConstraint(
            model_name="seasonreward",
            constraint=models.UniqueConstraint(
                fields=("season", "user"), name="unique_season_reward"
            ),
        ),
    ]
