# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("leagues", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="leaguestanding",
            name="user",
            field=models.ForeignKey(
                help_text="The user this standing belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="league_standings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(fields=["is_active"], name="idx_season_active"),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["start_date", "end_date"], name="idx_season_dates"
            ),
        ),
        migrations.AddField(
            model_name="leaguestanding",
            name="season",
            field=models.ForeignKey(
                help_text="The season this standing applies to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="standings",
                to="leagues.season",
            ),
        ),
        migrations.AddField(
            model_name="seasonreward",
            name="league_achieved",
            field=models.ForeignKey(
                help_text="The league the user was in when the season ended.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rewards",
                to="leagues.league",
            ),
        ),
        migrations.AddField(
            model_name="seasonreward",
            name="season",
            field=models.ForeignKey(
                help_text="The season this reward is from.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rewards",
                to="leagues.season",
            ),
        ),
        migrations.AddField(
            model_name="seasonreward",
            name="user",
            field=models.ForeignKey(
                help_text="The user who earned this reward.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="season_rewards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["season", "rank"], name="idx_standing_season_rank"
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["season", "league", "-xp_earned_this_season"],
                name="idx_standing_league_xp",
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["season", "-xp_earned_this_season"],
                name="idx_standing_season_xp",
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["user", "season"], name="idx_standing_user_season"
            ),
        ),
        migrations.AddIndex(
            model_name="leaguestanding",
            index=models.Index(
                fields=["league", "rank"], name="idx_standing_league_rank"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaguestanding",
            unique_together={("user", "season")},
        ),
        migrations.AddIndex(
            model_name="seasonreward",
            index=models.Index(
                fields=["user", "rewards_claimed"], name="idx_reward_user_claimed"
            ),
        ),
        migrations.AddIndex(
            model_name="seasonreward",
            index=models.Index(
                fields=["season", "league_achieved"], name="idx_reward_season_league"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seasonreward",
            unique_together={("season", "user")},
        ),
    ]
