# Generated by Django 5.2.11 on 2026-02-27 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_ranksnapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaguestanding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ranksnapshot',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seasonreward',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='leaguestanding',
            constraint=models.UniqueConstraint(fields=('user', 'season'), name='unique_league_standing'),
        ),
        migrations.AddConstraint(
            model_name='ranksnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'season', 'snapshot_date'), name='unique_rank_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='seasonreward',
            constraint=models.UniqueConstraint(fields=('season', 'user'), name='unique_season_reward'),
        ),
    ]
