# Generated by Django 5.2.11 on 2026-03-04 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_alter_leaguestanding_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this league season.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Display name of the season (e.g., "Season of Growth - Spring 2026").', max_length=200)),
                ('theme', models.CharField(choices=[('growth', 'Growth'), ('fire', 'Fire'), ('ocean', 'Ocean'), ('cosmic', 'Cosmic'), ('aurora', 'Aurora'), ('crystal', 'Crystal'), ('storm', 'Storm'), ('bloom', 'Bloom')], default='growth', help_text='Visual theme for the season (growth, fire, ocean, cosmic, etc.).', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the season theme and what makes it special.')),
                ('start_date', models.DateField(help_text='When this season starts.')),
                ('end_date', models.DateField(help_text='When this season ends.')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this season is currently active. Only one should be active at a time.')),
                ('rewards', models.JSONField(blank=True, default=list, help_text='Tiered reward definitions. Each entry: {"rank_min": 1, "rank_max": 3, "reward_type": "badge", "reward_id": "gold_crown", "title": "Gold Crown Badge"}.')),
                ('theme_colors', models.JSONField(blank=True, default=dict, help_text='Theme color palette: {"primary": "#hex", "secondary": "#hex", "accent": "#hex"}.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'League Season',
                'verbose_name_plural': 'League Seasons',
                'db_table': 'league_seasons',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active'], name='idx_lseason_active'), models.Index(fields=['start_date', 'end_date'], name='idx_lseason_dates')],
            },
        ),
        migrations.CreateModel(
            name='SeasonParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this participant record.', primary_key=True, serialize=False)),
                ('xp_earned', models.PositiveIntegerField(default=0, help_text='Total XP earned during this season.')),
                ('rank', models.PositiveIntegerField(blank=True, help_text='Final rank in the season (computed from XP).', null=True)),
                ('rewards_claimed', models.BooleanField(default=False, help_text='Whether the user has claimed their end-of-season rewards.')),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this season.')),
                ('season', models.ForeignKey(help_text='The league season this participation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='leagues.leagueseason')),
                ('user', models.ForeignKey(help_text='The user participating in the season.', on_delete=django.db.models.deletion.CASCADE, related_name='season_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Season Participant',
                'verbose_name_plural': 'Season Participants',
                'db_table': 'season_participants',
                'ordering': ['-xp_earned'],
                'indexes': [models.Index(fields=['season', '-xp_earned'], name='idx_sparticipant_season_xp'), models.Index(fields=['season', 'rank'], name='idx_sparticipant_season_rank'), models.Index(fields=['user', 'season'], name='idx_sparticipant_user_season')],
                'unique_together': {('season', 'user')},
            },
        ),
    ]
