# Generated by Django 5.0.14 on 2026-03-10 02:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0005_leagueseason_seasonparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_number', models.PositiveIntegerField(help_text='Group number within this season+league (1-indexed).')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this group is active (False after season ends or rebalance empties it).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'League Group',
                'verbose_name_plural': 'League Groups',
                'db_table': 'league_groups',
                'ordering': ['season', 'league', 'group_number'],
            },
        ),
        migrations.CreateModel(
            name='LeagueGroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user was assigned to this group.')),
            ],
            options={
                'verbose_name': 'League Group Membership',
                'verbose_name_plural': 'League Group Memberships',
                'db_table': 'league_group_memberships',
            },
        ),
        migrations.CreateModel(
            name='SeasonConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season_duration_days', models.PositiveIntegerField(default=180, help_text='Default duration in days for new seasons.')),
                ('group_target_size', models.PositiveIntegerField(default=20, help_text='Target number of members per group.')),
                ('group_max_size', models.PositiveIntegerField(default=30, help_text='Maximum number of members allowed per group.')),
                ('group_min_size', models.PositiveIntegerField(default=5, help_text='Minimum number of members to keep a group active.')),
                ('promotion_xp_threshold', models.PositiveIntegerField(default=1000, help_text='XP earned this season to be eligible for promotion.')),
                ('relegation_xp_threshold', models.PositiveIntegerField(default=100, help_text='XP below this threshold triggers relegation risk.')),
                ('auto_create_next_season', models.BooleanField(default=True, help_text='Automatically create the next season when one ends.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Season Config',
                'verbose_name_plural': 'Season Config',
                'db_table': 'season_config',
            },
        ),
        migrations.AddField(
            model_name='season',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the season in days (stored at creation time).', null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('processing', 'Processing'), ('ended', 'Ended')], db_index=True, default='pending', help_text='Lifecycle status of the season.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['status'], name='idx_season_status'),
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='league',
            field=models.ForeignKey(help_text='The league tier this group is in.', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='leagues.league'),
        ),
        migrations.AddField(
            model_name='leaguegroup',
            name='season',
            field=models.ForeignKey(help_text='The season this group belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='leagues.season'),
        ),
        migrations.AddField(
            model_name='leaguegroupmembership',
            name='group',
            field=models.ForeignKey(help_text='The group this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='leagues.leaguegroup'),
        ),
        migrations.AddField(
            model_name='leaguegroupmembership',
            name='promoted_from_group',
            field=models.ForeignKey(blank=True, help_text='The group the user was promoted from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_out', to='leagues.leaguegroup'),
        ),
        migrations.AddField(
            model_name='leaguegroupmembership',
            name='standing',
            field=models.OneToOneField(help_text='The league standing this membership is for.', on_delete=django.db.models.deletion.CASCADE, related_name='group_membership', to='leagues.leaguestanding'),
        ),
        migrations.AddIndex(
            model_name='leaguegroup',
            index=models.Index(fields=['season', 'league', 'is_active'], name='idx_lg_season_league_active'),
        ),
        migrations.AddConstraint(
            model_name='leaguegroup',
            constraint=models.UniqueConstraint(fields=('season', 'league', 'group_number'), name='unique_league_group'),
        ),
        migrations.AddIndex(
            model_name='leaguegroupmembership',
            index=models.Index(fields=['group'], name='idx_lgm_group'),
        ),
    ]
