# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarShare",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[
                            ("view", "View Only"),
                            ("suggest", "Can Suggest Times"),
                        ],
                        default="view",
                        help_text="Permission level: view only or can suggest times.",
                        max_length=10,
                    ),
                ),
                (
                    "share_token",
                    models.CharField(
                        blank=True,
                        help_text="Unique token for link-based calendar sharing.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this share is currently active.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Calendar Share",
                "verbose_name_plural": "Calendar Shares",
                "db_table": "calendar_shares",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoogleCalendarIntegration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("access_token", encrypted_model_fields.fields.EncryptedTextField()),
                ("refresh_token", encrypted_model_fields.fields.EncryptedTextField()),
                ("token_expiry", models.DateTimeField()),
                (
                    "calendar_id",
                    models.CharField(
                        default="primary",
                        help_text="Google Calendar ID to sync with.",
                        max_length=255,
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_token",
                    models.CharField(
                        blank=True,
                        help_text="Google incremental sync token.",
                        max_length=500,
                    ),
                ),
                (
                    "synced_dream_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of dream UUIDs to sync. Empty = sync all.",
                    ),
                ),
                (
                    "sync_direction",
                    models.CharField(
                        choices=[
                            ("both", "Both ways"),
                            ("push_only", "Push only"),
                            ("pull_only", "Pull only"),
                        ],
                        default="both",
                        help_text="Direction of sync with Google Calendar.",
                        max_length=10,
                    ),
                ),
                (
                    "sync_tasks",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to sync dream tasks as calendar events.",
                    ),
                ),
                (
                    "sync_events",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to sync standalone calendar events.",
                    ),
                ),
                (
                    "ical_feed_token",
                    models.CharField(
                        blank=True,
                        help_text="Secret token for iCal feed URL.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "google_calendar_integrations",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekdays", "Weekdays"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        default="daily",
                        max_length=10,
                    ),
                ),
                (
                    "custom_days",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of day numbers 0-6 (Mon-Sun) for custom frequency.",
                    ),
                ),
                (
                    "target_per_day",
                    models.IntegerField(
                        default=1,
                        help_text="How many times per day to complete the habit.",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#8B5CF6",
                        help_text="Hex color code for the habit.",
                        max_length=7,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="star",
                        help_text="Lucide icon name for the habit.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("streak_current", models.IntegerField(default=0)),
                ("streak_best", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "habits",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitCompletion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "count",
                    models.IntegerField(
                        default=1, help_text="Number of completions for this date."
                    ),
                ),
                (
                    "note",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
            ],
            options={
                "db_table": "habit_completions",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="RecurrenceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_date",
                    models.DateField(
                        help_text="The original occurrence date being modified or skipped."
                    ),
                ),
                (
                    "skip_occurrence",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the occurrence on original_date is skipped entirely.",
                    ),
                ),
                (
                    "modified_title",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Modified title for this occurrence (blank = use parent title).",
                    ),
                ),
                (
                    "modified_start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Modified start time for this occurrence.",
                        null=True,
                    ),
                ),
                (
                    "modified_end_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Modified end time for this occurrence.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recurrence_exceptions",
                "ordering": ["original_date"],
            },
        ),
        migrations.CreateModel(
            name="TimeBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("work", "Work"),
                            ("personal", "Personal"),
                            ("family", "Family"),
                            ("exercise", "Exercise"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=20,
                    ),
                ),
                ("day_of_week", models.IntegerField(help_text="0=Monday, 6=Sunday")),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "focus_block",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this time block is a focus/DND block that suppresses notifications.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "time_blocks",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeBlockTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "blocks",
                    models.JSONField(
                        help_text="Array of {block_type, day_of_week, start_time, end_time}"
                    ),
                ),
                (
                    "is_preset",
                    models.BooleanField(
                        default=False, help_text="System-provided preset template"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "timeblock_templates",
                "ordering": ["-is_preset", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField()),
                (
                    "all_day",
                    models.BooleanField(
                        default=False, help_text="Whether this is an all-day event."
                    ),
                ),
                (
                    "event_timezone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional timezone override for this event (e.g. America/New_York). Empty = use user home timezone.",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    encrypted_model_fields.fields.EncryptedCharField(blank=True),
                ),
                ("reminder_minutes_before", models.IntegerField(default=15)),
                (
                    "reminders",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of reminders: [{minutes_before: int, type: "push"|"email"}]',
                    ),
                ),
                (
                    "reminders_sent",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of reminder keys already sent, e.g. ["15_2026-03-04T10:00:00"]',
                    ),
                ),
                (
                    "snoozed_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, suppress in-app notification popups until this datetime.",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("deadline", "Deadline"),
                            ("milestone", "Milestone"),
                            ("habit", "Habit"),
                            ("social", "Social"),
                            ("health", "Health"),
                            ("learning", "Learning"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        default="custom",
                        help_text="Event category for visual grouping and filtering.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("is_recurring", models.BooleanField(default=False)),
                (
                    "recurrence_rule",
                    models.JSONField(
                        blank=True,
                        help_text='Recurrence rule: {frequency: "daily|weekly|monthly|yearly|custom", interval: int, days_of_week: [0-6], day_of_month: int, week_of_month: int, day_of_week: int, end_date: "ISO"|null, end_after_count: int|null, weekdays_only: bool}',
                        null=True,
                    ),
                ),
                (
                    "google_event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Google Calendar event ID for bidirectional sync.",
                        max_length=255,
                    ),
                ),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("local", "Local only"),
                            ("synced", "Synced"),
                            ("pending", "Pending sync"),
                            ("error", "Sync error"),
                        ],
                        db_index=True,
                        default="local",
                        help_text="Google Calendar sync status for this event.",
                        max_length=10,
                    ),
                ),
                (
                    "last_sync_error",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Last sync error message, if any.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent event if this is a recurring instance.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_instances",
                        to="calendar.calendarevent",
                    ),
                ),
            ],
            options={
                "db_table": "calendar_events",
                "ordering": ["start_time"],
            },
        ),
    ]
