# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("calendar", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendar_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calendarshare",
            name="owner",
            field=models.ForeignKey(
                help_text="The user who owns the calendar being shared.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_calendars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calendarshare",
            name="shared_with",
            field=models.ForeignKey(
                blank=True,
                help_text="The user the calendar is shared with. Null for link-only shares.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calendars_shared_with_me",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="googlecalendarintegration",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_calendar",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="habitcompletion",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="calendar.habit",
            ),
        ),
        migrations.AddField(
            model_name="recurrenceexception",
            name="parent_event",
            field=models.ForeignKey(
                help_text="The recurring parent event this exception belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exceptions",
                to="calendar.calendarevent",
            ),
        ),
        migrations.AddField(
            model_name="timeblock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_blocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timeblocktemplate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeblock_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["user", "start_time"], name="calendar_ev_user_id_26e211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(fields=["status"], name="calendar_ev_status_453150_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarshare",
            index=models.Index(
                fields=["owner", "is_active"], name="idx_calshare_owner_active"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarshare",
            index=models.Index(
                fields=["shared_with", "is_active"], name="idx_calshare_shared_active"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarshare",
            index=models.Index(fields=["share_token"], name="idx_calshare_token"),
        ),
        migrations.AlterUniqueTogether(
            name="calendarshare",
            unique_together={("owner", "shared_with")},
        ),
        migrations.AddIndex(
            model_name="habit",
            index=models.Index(
                fields=["user", "is_active"], name="habits_user_id_41ce3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="habitcompletion",
            index=models.Index(
                fields=["habit", "date"], name="habit_compl_habit_i_aa6338_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="habitcompletion",
            unique_together={("habit", "date")},
        ),
        migrations.AddIndex(
            model_name="recurrenceexception",
            index=models.Index(
                fields=["parent_event", "original_date"],
                name="recurrence__parent__32e4b8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recurrenceexception",
            unique_together={("parent_event", "original_date")},
        ),
        migrations.AddIndex(
            model_name="timeblock",
            index=models.Index(
                fields=["user", "day_of_week", "is_active"],
                name="time_blocks_user_id_5fdfc4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeblock",
            index=models.Index(
                fields=["user", "focus_block", "is_active"],
                name="time_blocks_user_id_f81667_idx",
            ),
        ),
    ]
