# Generated by Django 5.0.14 on 2026-03-22 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_initial'),
        ('dreams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='color',
            field=models.CharField(blank=True, default='#8B5CF6', help_text='Hex color code for the time block.', max_length=7),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='dream',
            field=models.ForeignKey(blank=True, help_text='Optional associated dream.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_blocks', to='dreams.dream'),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Optional user-facing label for this time block.', max_length=200),
        ),
        migrations.AlterField(
            model_name='timeblock',
            name='block_type',
            field=models.CharField(choices=[('work', 'Work'), ('personal', 'Personal'), ('family', 'Family'), ('exercise', 'Exercise'), ('blocked', 'Blocked')], default='personal', max_length=20),
        ),
    ]
