# Generated by Django 5.2.6 on 2026-02-24 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0004_calendarevent_is_recurring_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="timeblock",
            index=models.Index(
                fields=["user", "day_of_week", "is_active"],
                name="time_blocks_user_id_5fdfc4_idx",
            ),
        ),
    ]
