# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar", "0005_timeblock_time_blocks_user_id_5fdfc4_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendarevent",
            name="description",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True, default=""
            ),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="location",
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name="googlecalendarintegration",
            name="access_token",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name="googlecalendarintegration",
            name="refresh_token",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
