# Generated by Django 5.2.11 on 2026-03-04 10:03

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0008_calendarevent_all_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='sync_direction',
            field=models.CharField(choices=[('both', 'Both ways'), ('push_only', 'Push only'), ('pull_only', 'Pull only')], default='both', help_text='Direction of sync with Google Calendar.', max_length=10),
        ),
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='sync_events',
            field=models.BooleanField(default=True, help_text='Whether to sync standalone calendar events.'),
        ),
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='sync_tasks',
            field=models.BooleanField(default=True, help_text='Whether to sync dream tasks as calendar events.'),
        ),
        migrations.AddField(
            model_name='googlecalendarintegration',
            name='synced_dream_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of dream UUIDs to sync. Empty = sync all.'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence_rule',
            field=models.JSONField(blank=True, help_text='Recurrence rule: {frequency: "daily|weekly|monthly|yearly|custom", interval: int, days_of_week: [0-6], day_of_month: int, week_of_month: int, day_of_week: int, end_date: "ISO"|null, end_after_count: int|null, weekdays_only: bool}', null=True),
        ),
        migrations.CreateModel(
            name='TimeBlockTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('blocks', models.JSONField(help_text='Array of {block_type, day_of_week, start_time, end_time}')),
                ('is_preset', models.BooleanField(default=False, help_text='System-provided preset template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeblock_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timeblock_templates',
                'ordering': ['-is_preset', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_date', models.DateField(help_text='The original occurrence date being modified or skipped.')),
                ('skip_occurrence', models.BooleanField(default=False, help_text='If True, the occurrence on original_date is skipped entirely.')),
                ('modified_title', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Modified title for this occurrence (blank = use parent title).')),
                ('modified_start_time', models.DateTimeField(blank=True, help_text='Modified start time for this occurrence.', null=True)),
                ('modified_end_time', models.DateTimeField(blank=True, help_text='Modified end time for this occurrence.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_event', models.ForeignKey(help_text='The recurring parent event this exception belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendar.calendarevent')),
            ],
            options={
                'db_table': 'recurrence_exceptions',
                'ordering': ['original_date'],
                'indexes': [models.Index(fields=['parent_event', 'original_date'], name='recurrence__parent__32e4b8_idx')],
                'unique_together': {('parent_event', 'original_date')},
            },
        ),
    ]
