# Generated by Django 5.2.11 on 2026-03-04 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0009_selective_sync_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='focus_block',
            field=models.BooleanField(default=False, help_text='Whether this time block is a focus/DND block that suppresses notifications.'),
        ),
        migrations.AddIndex(
            model_name='timeblock',
            index=models.Index(fields=['user', 'focus_block', 'is_active'], name='time_blocks_user_id_f81667_idx'),
        ),
    ]
