# Generated by Django 5.2.11 on 2026-03-04 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0014_calendarevent_reminders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view', 'View Only'), ('suggest', 'Can Suggest Times')], default='view', help_text='Permission level: view only or can suggest times.', max_length=10)),
                ('share_token', models.CharField(blank=True, help_text='Unique token for link-based calendar sharing.', max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this share is currently active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Calendar Share',
                'verbose_name_plural': 'Calendar Shares',
                'db_table': 'calendar_shares',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='calendarshare',
            name='owner',
            field=models.ForeignKey(help_text='The user who owns the calendar being shared.', on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarshare',
            name='shared_with',
            field=models.ForeignKey(blank=True, help_text='The user the calendar is shared with. Null for link-only shares.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars_shared_with_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['owner', 'is_active'], name='idx_calshare_owner_active'),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['shared_with', 'is_active'], name='idx_calshare_shared_active'),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['share_token'], name='idx_calshare_token'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarshare',
            unique_together={('owner', 'shared_with')},
        ),
    ]
