# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0015_calendar_share_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='category',
            field=models.CharField(
                choices=[
                    ('meeting', 'Meeting'),
                    ('deadline', 'Deadline'),
                    ('milestone', 'Milestone'),
                    ('habit', 'Habit'),
                    ('social', 'Social'),
                    ('health', 'Health'),
                    ('learning', 'Learning'),
                    ('custom', 'Custom'),
                ],
                db_index=True,
                default='custom',
                help_text='Event category for visual grouping and filtering.',
                max_length=20,
            ),
        ),
    ]
