# Generated by Django 5.2.11 on 2026-03-04 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0016_calendarevent_category'),
        ('calendar', '0016_calendarevent_event_timezone'),
        ('calendar', '0016_calendarevent_snoozed_until'),
    ]

    operations = [
    ]
