# Generated by Django 5.2.11 on 2026-03-04 10:47

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0017_merge_20260304_1047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', encrypted_model_fields.fields.EncryptedCharField()),
                ('description', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=10)),
                ('custom_days', models.JSONField(blank=True, default=list, help_text='List of day numbers 0-6 (Mon-Sun) for custom frequency.')),
                ('target_per_day', models.IntegerField(default=1, help_text='How many times per day to complete the habit.')),
                ('color', models.CharField(default='#8B5CF6', help_text='Hex color code for the habit.', max_length=7)),
                ('icon', models.CharField(default='star', help_text='Lucide icon name for the habit.', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('streak_current', models.IntegerField(default=0)),
                ('streak_best', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True)),
                ('count', models.IntegerField(default=1, help_text='Number of completions for this date.')),
                ('note', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='calendar.habit')),
            ],
            options={
                'db_table': 'habit_completions',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'is_active'], name='habits_user_id_41ce3a_idx'),
        ),
        migrations.AddIndex(
            model_name='habitcompletion',
            index=models.Index(fields=['habit', 'date'], name='habit_compl_habit_i_aa6338_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='habitcompletion',
            unique_together={('habit', 'date')},
        ),
    ]
