# Generated by Django 5.1.15 on 2026-03-18 21:34

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0021_merge_20260310_0205"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("dream_creation", "Dream Creation"),
                            ("planning", "Planning"),
                            ("check_in", "Check In"),
                            ("adjustment", "Adjustment"),
                            ("general", "General"),
                            ("motivation", "Motivation"),
                            ("rescue", "Rescue"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Custom system prompt for this template."
                    ),
                ),
                (
                    "starter_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of starter message dicts: [{"role": "assistant", "content": "..."}]',
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to users when browsing templates.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon identifier for the template.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_conversation_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("dream_creation", "Dream Creation"),
                            ("planning", "Planning"),
                            ("check_in", "Check In"),
                            ("adjustment", "Adjustment"),
                            ("general", "General"),
                            ("motivation", "Motivation"),
                            ("rescue", "Rescue"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Optional conversation title (encrypted at rest)",
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(
                        default=False, help_text="Whether this conversation is pinned"
                    ),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("total_tokens_used", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dream",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="dreams.dream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Message content (encrypted at rest)."
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the uploaded audio file for voice messages.",
                        max_length=500,
                    ),
                ),
                (
                    "audio_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the audio file in seconds.",
                        null=True,
                    ),
                ),
                (
                    "transcription",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Whisper transcription of the audio message (encrypted at rest).",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to an uploaded image for GPT-4 Vision analysis.",
                        max_length=500,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                (
                    "reactions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of reaction emojis"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ai.aiconversation",
                    ),
                ),
            ],
            options={
                "db_table": "ai_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMemory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("preference", "Preference"),
                            ("fact", "Fact"),
                            ("goal_context", "Goal Context"),
                            ("style", "Style"),
                        ],
                        db_index=True,
                        default="fact",
                        help_text="Memory category (preference, fact, goal_context, style).",
                        max_length=100,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="The remembered information (encrypted at rest)."
                    ),
                ),
                (
                    "importance",
                    models.IntegerField(
                        default=3,
                        help_text="Importance level from 1 (low) to 5 (critical).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_conversation",
                    models.ForeignKey(
                        blank=True,
                        help_text="AI conversation this memory was extracted from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="extracted_memories",
                        to="ai.aiconversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_chat_memories",
                "ordering": ["-importance", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ConversationBranch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional label for this branch.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="ai.aiconversation",
                    ),
                ),
                (
                    "parent_message",
                    models.ForeignKey(
                        help_text="The message from which this branch diverges.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="ai.aimessage",
                    ),
                ),
            ],
            options={
                "db_table": "ai_conversation_branches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="aimessage",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch this message belongs to (null = main conversation).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="ai.conversationbranch",
            ),
        ),
        migrations.CreateModel(
            name="ConversationSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("summary", encrypted_model_fields.fields.EncryptedTextField()),
                ("key_points", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="ai.aiconversation",
                    ),
                ),
                (
                    "end_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_ends",
                        to="ai.aimessage",
                    ),
                ),
                (
                    "start_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary_starts",
                        to="ai.aimessage",
                    ),
                ),
            ],
            options={
                "db_table": "ai_conversation_summaries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="ai_conversa_user_id_0309df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["conversation_type"], name="ai_conversa_convers_bdf9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmemory",
            index=models.Index(
                fields=["user", "-importance"], name="ai_chat_mem_user_id_ab28b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmemory",
            index=models.Index(
                fields=["user", "key"], name="ai_chat_mem_user_id_c2cd43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmemory",
            index=models.Index(
                fields=["user", "is_active"], name="ai_chat_mem_user_id_ef1a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbranch",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="ai_conversa_convers_9bae1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbranch",
            index=models.Index(
                fields=["parent_message"], name="ai_conversa_parent__89fa19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="ai_messages_convers_15163f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(fields=["role"], name="ai_messages_role_0601fb_idx"),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["branch", "created_at"], name="ai_messages_branch__4d4256_idx"
            ),
        ),
    ]
