# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0001_initial"),
        ("dreams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconversation",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ai_conversations",
                to="dreams.dream",
            ),
        ),
    ]
