# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="ai.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="chatmemory",
            name="source_conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="AI conversation this memory was extracted from.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="extracted_memories",
                to="ai.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="chatmemory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_chat_memories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conversationbranch",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="ai.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationbranch",
            name="parent_message",
            field=models.ForeignKey(
                help_text="The message from which this branch diverges.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="ai.aimessage",
            ),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                help_text="Branch this message belongs to (null = main conversation).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="ai.conversationbranch",
            ),
        ),
        migrations.AddField(
            model_name="conversationsummary",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summaries",
                to="ai.aiconversation",
            ),
        ),
        migrations.AddField(
            model_name="conversationsummary",
            name="end_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_ends",
                to="ai.aimessage",
            ),
        ),
        migrations.AddField(
            model_name="conversationsummary",
            name="start_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="summary_starts",
                to="ai.aimessage",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="ai_conversa_user_id_0309df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["conversation_type"], name="ai_conversa_convers_bdf9fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmemory",
            index=models.Index(
                fields=["user", "-importance"], name="ai_chat_mem_user_id_ab28b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmemory",
            index=models.Index(
                fields=["user", "key"], name="ai_chat_mem_user_id_c2cd43_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmemory",
            index=models.Index(
                fields=["user", "is_active"], name="ai_chat_mem_user_id_ef1a3f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbranch",
            index=models.Index(
                fields=["conversation", "-created_at"],
                name="ai_conversa_convers_9bae1a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationbranch",
            index=models.Index(
                fields=["parent_message"], name="ai_conversa_parent__89fa19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="ai_messages_convers_15163f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(fields=["role"], name="ai_messages_role_0601fb_idx"),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["branch", "created_at"], name="ai_messages_branch__4d4256_idx"
            ),
        ),
    ]
