# Generated by Django 5.2.6 on 2026-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buddypairing",
            name="best_encouragement_streak",
            field=models.IntegerField(
                default=0, help_text="Best-ever consecutive-day encouragement streak."
            ),
        ),
        migrations.AddField(
            model_name="buddypairing",
            name="encouragement_streak",
            field=models.IntegerField(
                default=0, help_text="Current consecutive-day encouragement streak."
            ),
        ),
        migrations.AddField(
            model_name="buddypairing",
            name="last_encouragement_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last encouragement sent in this pairing.",
                null=True,
            ),
        ),
    ]
