# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("circles", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChallengeProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "progress_value",
                    models.FloatField(
                        default=0,
                        help_text="Numeric progress value (interpretation depends on challenge).",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this progress update.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_entries",
                        to="circles.circlechallenge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "challenge_progress",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["challenge", "user", "-created_at"],
                        name="challenge_p_challen_73dc1f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CircleInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invite_code",
                    models.CharField(
                        db_index=True,
                        help_text="Shareable code for link-based invitations.",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When this invitation expires."),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="circles.circle",
                    ),
                ),
                (
                    "invitee",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user invited (null for link invitations).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_invites_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inviter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="circle_invites_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "circle_invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["invite_code"], name="circle_invi_invite__0062a8_idx"
                    ),
                    models.Index(
                        fields=["circle", "invitee", "status"],
                        name="circle_invi_circle__cc96c5_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("thumbs_up", "Thumbs Up"),
                            ("fire", "Fire"),
                            ("clap", "Clap"),
                            ("heart", "Heart"),
                        ],
                        help_text="Type of reaction.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        help_text="The post this reaction is on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="circles.circlepost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who reacted.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_reactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Post Reaction",
                "verbose_name_plural": "Post Reactions",
                "db_table": "post_reactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "reaction_type"], name="idx_reaction_post_type"
                    )
                ],
                "unique_together": {("post", "user")},
            },
        ),
    ]
