# Generated by Django 5.0.14 on 2026-03-20 19:09

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Optional reason for blocking (encrypted at rest).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Blocked User",
                "verbose_name_plural": "Blocked Users",
                "db_table": "blocked_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Friendship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this friendship.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="Current status of the friendship.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Friendship",
                "verbose_name_plural": "Friendships",
                "db_table": "friendships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Description of why the user is being reported (encrypted at rest)."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("harassment", "Harassment"),
                            ("inappropriate", "Inappropriate Content"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category of the report.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes from admin review.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reported User",
                "verbose_name_plural": "Reported Users",
                "db_table": "reported_users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserFollow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this follow.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "User Follow",
                "verbose_name_plural": "User Follows",
                "db_table": "user_follows",
                "ordering": ["-created_at"],
            },
        ),
    ]
