# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("friends", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blockeduser",
            name="blocked",
            field=models.ForeignKey(
                help_text="The user who was blocked.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="blockeduser",
            name="blocker",
            field=models.ForeignKey(
                help_text="The user who performed the block.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocked_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user1",
            field=models.ForeignKey(
                help_text="The user who sent the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user2",
            field=models.ForeignKey(
                help_text="The user who received the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporteduser",
            name="reported",
            field=models.ForeignKey(
                help_text="The user being reported.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporteduser",
            name="reporter",
            field=models.ForeignKey(
                help_text="The user who filed the report.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                help_text="The user who is following.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                help_text="The user being followed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="blockeduser",
            index=models.Index(fields=["blocker"], name="idx_blocked_blocker"),
        ),
        migrations.AddIndex(
            model_name="blockeduser",
            index=models.Index(fields=["blocked"], name="idx_blocked_blocked"),
        ),
        migrations.AddConstraint(
            model_name="blockeduser",
            constraint=models.UniqueConstraint(
                fields=("blocker", "blocked"), name="unique_blocker_blocked"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["user1", "status"], name="idx_friendship_user1_status"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["user2", "status"], name="idx_friendship_user2_status"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["status"], name="idx_friendship_status"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["-created_at"], name="idx_friendship_created"),
        ),
        migrations.AddConstraint(
            model_name="friendship",
            constraint=models.UniqueConstraint(
                fields=("user1", "user2"), name="unique_friendship_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="reporteduser",
            index=models.Index(fields=["status"], name="idx_report_status"),
        ),
        migrations.AddIndex(
            model_name="reporteduser",
            index=models.Index(fields=["-created_at"], name="idx_report_created"),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(fields=["follower"], name="idx_follow_follower"),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(fields=["following"], name="idx_follow_following"),
        ),
        migrations.AddConstraint(
            model_name="userfollow",
            constraint=models.UniqueConstraint(
                fields=("follower", "following"), name="unique_follower_following"
            ),
        ),
    ]
