# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dreams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dreams",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="calibrationresponse",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="calibration_responses",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="obstacle",
            name="dream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="obstacles",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="dreams.goal",
            ),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["user", "status"], name="dreams_user_id_f65fcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(fields=["category"], name="dreams_categor_913d7e_idx"),
        ),
        migrations.AddIndex(
            model_name="dream",
            index=models.Index(
                fields=["target_date"], name="dreams_target__080048_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="calibrationresponse",
            index=models.Index(
                fields=["dream", "question_number"],
                name="calibration_dream_i_995ace_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["dream", "order"], name="goals_dream_i_18d7f5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(fields=["status"], name="goals_status_6bb941_idx"),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["scheduled_start"], name="goals_schedul_a281e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["goal", "scheduled_date"], name="tasks_goal_id_686a81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["scheduled_date"], name="tasks_schedul_49269d_idx"
            ),
        ),
    ]
