# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DreamTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DreamTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("health", "Health & Fitness"),
                            ("career", "Career & Business"),
                            ("education", "Education & Learning"),
                            ("finance", "Finance & Savings"),
                            ("creative", "Creative & Arts"),
                            ("personal", "Personal Growth"),
                            ("social", "Social & Relationships"),
                            ("travel", "Travel & Adventure"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "template_goals",
                    models.JSONField(
                        default=list,
                        help_text="JSON array of goal templates: [{title, description, order, tasks: [{title, description, order, duration_mins}]}]",
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.IntegerField(
                        default=90,
                        help_text="Estimated number of days to complete this dream.",
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dream_templates",
                "ordering": ["-is_featured", "-usage_count"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="dream_templ_categor_25cfc7_idx",
                    ),
                    models.Index(
                        fields=["is_featured", "is_active"],
                        name="dream_templ_is_feat_f47c6a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DreamCollaborator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("collaborator", "Collaborator"),
                            ("viewer", "Viewer"),
                        ],
                        default="viewer",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collaborators",
                        to="dreams.dream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dream_collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dream_collaborators",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "role"], name="idx_collab_user_role"),
                    models.Index(
                        fields=["dream", "user"], name="idx_collab_dream_user"
                    ),
                ],
                "unique_together": {("dream", "user")},
            },
        ),
        migrations.CreateModel(
            name="DreamTagging",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taggings",
                        to="dreams.dream",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taggings",
                        to="dreams.dreamtag",
                    ),
                ),
            ],
            options={
                "db_table": "dream_taggings",
                "unique_together": {("dream", "tag")},
            },
        ),
        migrations.CreateModel(
            name="SharedDream",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("view", "View Only"), ("comment", "Can Comment")],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="dreams.dream",
                    ),
                ),
                (
                    "shared_by",
                    models.ForeignKey(
                        help_text="The user who shared the dream.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dreams_shared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ForeignKey(
                        help_text="The user the dream was shared with.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dreams_shared_with_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "shared_dreams",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["shared_with"], name="idx_shared_dream_recipient"
                    )
                ],
                "unique_together": {("dream", "shared_with")},
            },
        ),
    ]
