# Generated by Django 5.0.14 on 2026-03-20 19:09

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "text",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="The comment text (encrypted at rest)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Activity Comment",
                "verbose_name_plural": "Activity Comments",
                "db_table": "activity_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityFeedItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for this activity item.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("task_completed", "Task Completed"),
                            ("dream_completed", "Dream Completed"),
                            ("milestone_reached", "Milestone Reached"),
                            ("buddy_matched", "Buddy Matched"),
                            ("circle_joined", "Circle Joined"),
                            ("level_up", "Level Up"),
                            ("streak_milestone", "Streak Milestone"),
                            ("badge_earned", "Badge Earned"),
                        ],
                        db_index=True,
                        help_text="The type of activity.",
                        max_length=30,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured content data for the activity (e.g., task title, dream name).",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata for the activity.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Activity Feed Item",
                "verbose_name_plural": "Activity Feed Items",
                "db_table": "activity_feed_items",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Activity Like",
                "verbose_name_plural": "Activity Likes",
                "db_table": "activity_likes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamEncouragement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "encouragement_type",
                    models.CharField(
                        choices=[
                            ("you_got_this", "You Got This!"),
                            ("keep_going", "Keep Going!"),
                            ("inspired", "You Inspire Me!"),
                            ("proud", "So Proud!"),
                            ("fire", "On Fire!"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        help_text="Optional personal message (encrypted at rest).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_encouragements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Caption/description (encrypted at rest)."
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, help_text="Optional image URL."),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True,
                        help_text="Optional uploaded image.",
                        upload_to="dream_posts/",
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional uploaded video.",
                        upload_to="dream_posts/videos/",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional uploaded audio.",
                        upload_to="dream_posts/audio/",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                        ],
                        default="none",
                        help_text="Type of media attached to this post.",
                        max_length=10,
                    ),
                ),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("achievement", "Achievement"),
                            ("milestone", "Milestone"),
                            ("event", "Event"),
                        ],
                        db_index=True,
                        default="regular",
                        help_text="Type of post (regular, achievement, milestone, event).",
                        max_length=20,
                    ),
                ),
                (
                    "gofundme_url",
                    models.URLField(blank=True, help_text="External fundraising link."),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("followers", "Followers Only"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=15,
                    ),
                ),
                (
                    "likes_count",
                    models.IntegerField(
                        default=0, help_text="Denormalized like count."
                    ),
                ),
                (
                    "comments_count",
                    models.IntegerField(
                        default=0, help_text="Denormalized comment count."
                    ),
                ),
                ("shares_count", models.IntegerField(default=0)),
                (
                    "saves_count",
                    models.IntegerField(
                        default=0, help_text="Denormalized bookmark count."
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dream_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamPostComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Comment content (encrypted at rest)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_post_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DreamPostLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "dream_post_likes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostReaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("like", "Like"),
                            ("love", "Love"),
                            ("fire", "Fire"),
                            ("clap", "Clap"),
                            ("wow", "Wow"),
                            ("celebrate", "Celebrate"),
                        ],
                        help_text="Type of reaction.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Post Reaction",
                "verbose_name_plural": "Post Reactions",
                "db_table": "dream_post_reactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecentSearch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("query", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "search_type",
                    models.CharField(
                        choices=[
                            ("users", "Users"),
                            ("dreams", "Dreams"),
                            ("all", "All"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "recent_searches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "saved_posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", encrypted_model_fields.fields.EncryptedCharField()),
                (
                    "description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True, default=""
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Cover image for the event.",
                        upload_to="events/",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("virtual", "Virtual"),
                            ("physical", "Physical"),
                            ("challenge", "Challenge"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        help_text="Physical address (encrypted at rest).",
                    ),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, help_text="Virtual meeting URL."),
                ),
                ("start_time", models.DateTimeField(db_index=True)),
                ("end_time", models.DateTimeField()),
                (
                    "challenge_description",
                    encrypted_model_fields.fields.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="Detailed challenge rules/description (encrypted at rest).",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of participants. Null = unlimited.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("participants_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "social_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialEventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("registered", "Registered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="registered",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "social_event_registrations",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_file",
                    models.ImageField(
                        blank=True, help_text="Story image.", upload_to="stories/"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Story video.",
                        upload_to="stories/videos/",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=280)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Auto-set to created_at + 24 hours."
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoryView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
