# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dreams", "0002_initial"),
        ("plans", "0002_initial"),
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activitycomment",
            name="user",
            field=models.ForeignKey(
                help_text="The user who wrote the comment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityfeeditem",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Another user related to this activity (e.g., buddy partner).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_activity_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityfeeditem",
            name="user",
            field=models.ForeignKey(
                help_text="The user who performed the activity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="activity",
            field=models.ForeignKey(
                help_text="The activity feed item that was commented on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="social.activityfeeditem",
            ),
        ),
        migrations.AddField(
            model_name="activitylike",
            name="activity",
            field=models.ForeignKey(
                help_text="The activity feed item that was liked.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="social.activityfeeditem",
            ),
        ),
        migrations.AddField(
            model_name="activitylike",
            name="user",
            field=models.ForeignKey(
                help_text="The user who liked the activity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreamencouragement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_encouragements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreampost",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionally linked dream.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_posts",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="dreampost",
            name="linked_goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Goal that was completed (for achievement posts).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="celebration_posts",
                to="plans.goal",
            ),
        ),
        migrations.AddField(
            model_name="dreampost",
            name="linked_milestone",
            field=models.ForeignKey(
                blank=True,
                help_text="Milestone that was reached (for milestone posts).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="celebration_posts",
                to="plans.dreammilestone",
            ),
        ),
        migrations.AddField(
            model_name="dreampost",
            name="linked_task",
            field=models.ForeignKey(
                blank=True,
                help_text="Task that was completed (for achievement posts).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="celebration_posts",
                to="plans.task",
            ),
        ),
        migrations.AddField(
            model_name="dreampost",
            name="saved_by",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who bookmarked this post.",
                related_name="saved_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreampost",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dream_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreamencouragement",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="encouragements",
                to="social.dreampost",
            ),
        ),
        migrations.AddField(
            model_name="dreampostcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent comment for threaded replies.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="social.dreampostcomment",
            ),
        ),
        migrations.AddField(
            model_name="dreampostcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="social.dreampost",
            ),
        ),
        migrations.AddField(
            model_name="dreampostcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dream_post_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dreampostlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="social.dreampost",
            ),
        ),
        migrations.AddField(
            model_name="dreampostlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dream_post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="post",
            field=models.ForeignKey(
                help_text="The post that was reacted to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="social.dreampost",
            ),
        ),
        migrations.AddField(
            model_name="postreaction",
            name="user",
            field=models.ForeignKey(
                help_text="The user who reacted.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dream_post_reactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recentsearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recent_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savedpost",
            name="post",
            field=models.ForeignKey(
                help_text="The post that was saved.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saves",
                to="social.dreampost",
            ),
        ),
        migrations.AddField(
            model_name="savedpost",
            name="user",
            field=models.ForeignKey(
                help_text="The user who saved the post.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_dream_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialevent",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialevent",
            name="dream",
            field=models.ForeignKey(
                blank=True,
                help_text="Optionally linked dream.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_events",
                to="dreams.dream",
            ),
        ),
        migrations.AddField(
            model_name="socialevent",
            name="post",
            field=models.ForeignKey(
                blank=True,
                help_text="The post announcing this event in the feed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="social_event",
                to="social.dreampost",
            ),
        ),
        migrations.AddField(
            model_name="socialeventregistration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registrations",
                to="social.socialevent",
            ),
        ),
        migrations.AddField(
            model_name="socialeventregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="storyview",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="social.story",
            ),
        ),
        migrations.AddField(
            model_name="storyview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_activity_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(fields=["activity_type"], name="idx_activity_type"),
        ),
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(fields=["-created_at"], name="idx_activity_created"),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(
                fields=["activity", "created_at"], name="idx_activity_comment_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="activitycomment",
            index=models.Index(fields=["user"], name="idx_activity_comment_user"),
        ),
        migrations.AddIndex(
            model_name="activitylike",
            index=models.Index(fields=["activity"], name="idx_activity_like_activity"),
        ),
        migrations.AddIndex(
            model_name="activitylike",
            index=models.Index(fields=["user"], name="idx_activity_like_user"),
        ),
        migrations.AddConstraint(
            model_name="activitylike",
            constraint=models.UniqueConstraint(
                fields=("user", "activity"), name="unique_user_activity_like"
            ),
        ),
        migrations.AddIndex(
            model_name="dreampost",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_dreampost_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="dreampost",
            index=models.Index(fields=["-created_at"], name="idx_dreampost_created"),
        ),
        migrations.AddIndex(
            model_name="dreampost",
            index=models.Index(fields=["visibility"], name="idx_dreampost_visibility"),
        ),
        migrations.AddIndex(
            model_name="dreampost",
            index=models.Index(fields=["post_type"], name="idx_dreampost_post_type"),
        ),
        migrations.AddConstraint(
            model_name="dreamencouragement",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_dreampost_encouragement"
            ),
        ),
        migrations.AddIndex(
            model_name="dreampostcomment",
            index=models.Index(
                fields=["post", "-created_at"], name="idx_dreamcomment_post_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="dreampostlike",
            constraint=models.UniqueConstraint(
                fields=("post", "user"), name="unique_dreampost_like"
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(
                fields=["post", "reaction_type"], name="idx_dreact_post_type"
            ),
        ),
        migrations.AddIndex(
            model_name="postreaction",
            index=models.Index(fields=["user"], name="idx_dreact_user"),
        ),
        migrations.AddConstraint(
            model_name="postreaction",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_dreampost_reaction"
            ),
        ),
        migrations.AddIndex(
            model_name="recentsearch",
            index=models.Index(
                fields=["user", "-created_at"], name="recent_sear_user_id_5793cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedpost",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_savedpost_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="savedpost",
            index=models.Index(fields=["post"], name="idx_savedpost_post"),
        ),
        migrations.AlterUniqueTogether(
            name="savedpost",
            unique_together={("user", "post")},
        ),
        migrations.AddIndex(
            model_name="socialevent",
            index=models.Index(
                fields=["creator", "-created_at"], name="idx_sevent_creator_date"
            ),
        ),
        migrations.AddIndex(
            model_name="socialevent",
            index=models.Index(fields=["event_type"], name="idx_sevent_type"),
        ),
        migrations.AddIndex(
            model_name="socialevent",
            index=models.Index(
                fields=["status", "start_time"], name="idx_sevent_status_start"
            ),
        ),
        migrations.AddIndex(
            model_name="socialevent",
            index=models.Index(fields=["-created_at"], name="idx_sevent_created"),
        ),
        migrations.AddIndex(
            model_name="socialeventregistration",
            index=models.Index(
                fields=["event", "status"], name="idx_sevent_reg_event_status"
            ),
        ),
        migrations.AddIndex(
            model_name="socialeventregistration",
            index=models.Index(fields=["user"], name="idx_sevent_reg_user"),
        ),
        migrations.AddConstraint(
            model_name="socialeventregistration",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_registration"
            ),
        ),
        migrations.AddConstraint(
            model_name="storyview",
            constraint=models.UniqueConstraint(
                fields=("story", "user"), name="unique_story_view"
            ),
        ),
    ]
