# Generated by Django 5.0.1 on 2026-02-05 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("social", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activityfeeditem",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                help_text="Another user related to this activity (e.g., buddy partner).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_activity_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityfeeditem",
            name="user",
            field=models.ForeignKey(
                help_text="The user who performed the activity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user1",
            field=models.ForeignKey(
                help_text="The user who sent the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_sent",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="friendship",
            name="user2",
            field=models.ForeignKey(
                help_text="The user who received the friend request.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friendships_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="follower",
            field=models.ForeignKey(
                help_text="The user who is following.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfollow",
            name="following",
            field=models.ForeignKey(
                help_text="The user being followed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers_set",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_activity_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(fields=["activity_type"], name="idx_activity_type"),
        ),
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(fields=["-created_at"], name="idx_activity_created"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["user1", "status"], name="idx_friendship_user1_status"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(
                fields=["user2", "status"], name="idx_friendship_user2_status"
            ),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["status"], name="idx_friendship_status"),
        ),
        migrations.AddIndex(
            model_name="friendship",
            index=models.Index(fields=["-created_at"], name="idx_friendship_created"),
        ),
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together={("user1", "user2")},
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(fields=["follower"], name="idx_follow_follower"),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(fields=["following"], name="idx_follow_following"),
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("follower", "following")},
        ),
    ]
