# Generated by Django 5.1.4 on 2026-03-25 05:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="activityfeeditem",
            index=models.Index(
                fields=["user", "activity_type", "-created_at"],
                name="idx_activity_user_type_date",
            ),
        ),
    ]
