# Generated by Django 5.0.6 on 2026-02-22 22:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_blockeduser_reporteduser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=200)),
                ('search_type', models.CharField(choices=[('users', 'Users'), ('dreams', 'Dreams'), ('all', 'All')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recent_searches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='recent_sear_user_id_5793cc_idx')],
            },
        ),
    ]
