# Generated by Django 5.0.6 on 2026-02-22 23:47

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_recentsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockeduser',
            name='reason',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Optional reason for blocking (encrypted at rest).'),
        ),
        migrations.AlterField(
            model_name='reporteduser',
            name='reason',
            field=encrypted_model_fields.fields.EncryptedTextField(help_text='Description of why the user is being reported (encrypted at rest).'),
        ),
    ]
