# Generated by Django 5.2.6 on 2026-02-24 06:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0005_alter_blockeduser_reason_alter_reporteduser_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text", models.TextField(help_text="The comment text.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="The activity feed item that was commented on.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="social.activityfeeditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who wrote the comment.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Comment",
                "verbose_name_plural": "Activity Comments",
                "db_table": "activity_comments",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["activity", "created_at"],
                        name="idx_activity_comment_activity",
                    ),
                    models.Index(fields=["user"], name="idx_activity_comment_user"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ActivityLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        help_text="The activity feed item that was liked.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="social.activityfeeditem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who liked the activity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Like",
                "verbose_name_plural": "Activity Likes",
                "db_table": "activity_likes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activity"], name="idx_activity_like_activity"
                    ),
                    models.Index(fields=["user"], name="idx_activity_like_user"),
                ],
                "unique_together": {("user", "activity")},
            },
        ),
    ]
