# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0006_activitycomment_activitylike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitycomment",
            name="text",
            field=encrypted_model_fields.fields.EncryptedTextField(
                help_text="The comment text (encrypted at rest)."
            ),
        ),
        migrations.AlterField(
            model_name="recentsearch",
            name="query",
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
