# Generated by Django 5.2.11 on 2026-02-27 03:40

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0007_alter_dream_description'),
        ('social', '0007_alter_activitycomment_text_alter_recentsearch_query'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DreamPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', encrypted_model_fields.fields.EncryptedTextField(help_text='Caption/description (encrypted at rest).')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL.')),
                ('image_file', models.ImageField(blank=True, help_text='Optional uploaded image.', upload_to='dream_posts/')),
                ('gofundme_url', models.URLField(blank=True, help_text='External fundraising link.')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only'), ('private', 'Private')], db_index=True, default='public', max_length=15)),
                ('likes_count', models.IntegerField(default=0, help_text='Denormalized like count.')),
                ('comments_count', models.IntegerField(default=0, help_text='Denormalized comment count.')),
                ('shares_count', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dream', models.ForeignKey(blank=True, help_text='Optionally linked dream.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='dreams.dream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dream_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamEncouragement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encouragement_type', models.CharField(choices=[('you_got_this', 'You Got This!'), ('keep_going', 'Keep Going!'), ('inspired', 'You Inspire Me!'), ('proud', 'So Proud!'), ('fire', 'On Fire!')], max_length=20)),
                ('message', encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Optional personal message (encrypted at rest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_encouragements', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encouragements', to='social.dreampost')),
            ],
            options={
                'db_table': 'dream_encouragements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamPostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', encrypted_model_fields.fields.EncryptedTextField(help_text='Comment content (encrypted at rest).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment for threaded replies.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='social.dreampostcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.dreampost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_post_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dream_post_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DreamPostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='social.dreampost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_post_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dream_post_likes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dreampost',
            index=models.Index(fields=['user', '-created_at'], name='idx_dreampost_user_date'),
        ),
        migrations.AddIndex(
            model_name='dreampost',
            index=models.Index(fields=['-created_at'], name='idx_dreampost_created'),
        ),
        migrations.AddIndex(
            model_name='dreampost',
            index=models.Index(fields=['visibility'], name='idx_dreampost_visibility'),
        ),
        migrations.AlterUniqueTogether(
            name='dreamencouragement',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='dreampostcomment',
            index=models.Index(fields=['post', '-created_at'], name='idx_dreamcomment_post_date'),
        ),
        migrations.AlterUniqueTogether(
            name='dreampostlike',
            unique_together={('post', 'user')},
        ),
    ]
