# Generated by Django 5.2.11 on 2026-02-27 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_dreampost_dreamencouragement_dreampostcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activitylike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dreamencouragement',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='dreampostlike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userfollow',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='activitylike',
            constraint=models.UniqueConstraint(fields=('user', 'activity'), name='unique_user_activity_like'),
        ),
        migrations.AddConstraint(
            model_name='blockeduser',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_blocker_blocked'),
        ),
        migrations.AddConstraint(
            model_name='dreamencouragement',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_dreampost_encouragement'),
        ),
        migrations.AddConstraint(
            model_name='dreampostlike',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_dreampost_like'),
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_friendship_pair'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='unique_follower_following'),
        ),
    ]
