# Generated by Django 5.0.1 on 2026-03-02 03:57

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreams', '0013_alter_goal_options_and_more'),
        ('social', '0009_alter_activitylike_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', encrypted_model_fields.fields.EncryptedCharField()),
                ('description', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the event.', upload_to='events/')),
                ('event_type', models.CharField(choices=[('virtual', 'Virtual'), ('physical', 'Physical'), ('challenge', 'Challenge')], db_index=True, max_length=20)),
                ('location', encrypted_model_fields.fields.EncryptedCharField(blank=True, default='', help_text='Physical address (encrypted at rest).')),
                ('meeting_link', models.URLField(blank=True, help_text='Virtual meeting URL.')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('challenge_description', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', help_text='Detailed challenge rules/description (encrypted at rest).')),
                ('max_participants', models.IntegerField(blank=True, help_text='Maximum number of participants. Null = unlimited.', null=True)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20)),
                ('participants_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'social_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialEventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'social_event_registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='dreampost',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Optional uploaded audio.', upload_to='dream_posts/audio/'),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='linked_goal',
            field=models.ForeignKey(blank=True, help_text='Goal that was completed (for achievement posts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebration_posts', to='dreams.goal'),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='linked_milestone',
            field=models.ForeignKey(blank=True, help_text='Milestone that was reached (for milestone posts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebration_posts', to='dreams.dreammilestone'),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text='Task that was completed (for achievement posts).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='celebration_posts', to='dreams.task'),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='media_type',
            field=models.CharField(choices=[('none', 'None'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], default='none', help_text='Type of media attached to this post.', max_length=10),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='post_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('achievement', 'Achievement'), ('milestone', 'Milestone'), ('event', 'Event')], db_index=True, default='regular', help_text='Type of post (regular, achievement, milestone, event).', max_length=20),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='saved_by',
            field=models.ManyToManyField(blank=True, help_text='Users who bookmarked this post.', related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='saves_count',
            field=models.IntegerField(default=0, help_text='Denormalized bookmark count.'),
        ),
        migrations.AddField(
            model_name='dreampost',
            name='video_file',
            field=models.FileField(blank=True, help_text='Optional uploaded video.', upload_to='dream_posts/videos/'),
        ),
        migrations.AddIndex(
            model_name='dreampost',
            index=models.Index(fields=['post_type'], name='idx_dreampost_post_type'),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='dream',
            field=models.ForeignKey(blank=True, help_text='Optionally linked dream.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_events', to='dreams.dream'),
        ),
        migrations.AddField(
            model_name='socialevent',
            name='post',
            field=models.ForeignKey(blank=True, help_text='The post announcing this event in the feed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_event', to='social.dreampost'),
        ),
        migrations.AddField(
            model_name='socialeventregistration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='social.socialevent'),
        ),
        migrations.AddField(
            model_name='socialeventregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='socialevent',
            index=models.Index(fields=['creator', '-created_at'], name='idx_sevent_creator_date'),
        ),
        migrations.AddIndex(
            model_name='socialevent',
            index=models.Index(fields=['event_type'], name='idx_sevent_type'),
        ),
        migrations.AddIndex(
            model_name='socialevent',
            index=models.Index(fields=['status', 'start_time'], name='idx_sevent_status_start'),
        ),
        migrations.AddIndex(
            model_name='socialevent',
            index=models.Index(fields=['-created_at'], name='idx_sevent_created'),
        ),
        migrations.AddIndex(
            model_name='socialeventregistration',
            index=models.Index(fields=['event', 'status'], name='idx_sevent_reg_event_status'),
        ),
        migrations.AddIndex(
            model_name='socialeventregistration',
            index=models.Index(fields=['user'], name='idx_sevent_reg_user'),
        ),
        migrations.AddConstraint(
            model_name='socialeventregistration',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_registration'),
        ),
    ]
