# Generated by Django 5.2.11 on 2026-03-04 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_story_storyview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='The post that was saved.', on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='social.dreampost')),
                ('user', models.ForeignKey(help_text='The user who saved the post.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_dream_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_savedpost_user_date'), models.Index(fields=['post'], name='idx_savedpost_post')],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
