# Generated by Django 5.2.11 on 2026-03-04 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_savedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('fire', 'Fire'), ('clap', 'Clap'), ('wow', 'Wow'), ('celebrate', 'Celebrate')], help_text='Type of reaction.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(help_text='The post that was reacted to.', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='social.dreampost')),
                ('user', models.ForeignKey(help_text='The user who reacted.', on_delete=django.db.models.deletion.CASCADE, related_name='dream_post_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post Reaction',
                'verbose_name_plural': 'Post Reactions',
                'db_table': 'dream_post_reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', 'reaction_type'], name='idx_dreact_post_type'), models.Index(fields=['user'], name='idx_dreact_user')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_dreampost_reaction')],
            },
        ),
    ]
