# Generated by Django 5.0.14 on 2026-03-20 19:09

import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("reminder", "Reminder"),
                            ("motivation", "Motivation"),
                            ("progress", "Progress"),
                            ("achievement", "Achievement"),
                            ("check_in", "Check In"),
                            ("rescue", "Rescue"),
                            ("buddy", "Buddy"),
                            ("missed_call", "Missed Call"),
                            ("system", "System"),
                            ("dream_completed", "Dream Completed"),
                            ("weekly_report", "Weekly Report"),
                            ("daily_summary", "Daily Summary"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    encrypted_model_fields.fields.EncryptedCharField(
                        help_text="Notification title (encrypted at rest)."
                    ),
                ),
                (
                    "body",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Notification body (encrypted at rest)."
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Additional data: {screen: "", dreamId: "", goalId: "", taskId: ""}',
                    ),
                ),
                ("scheduled_for", models.DateTimeField(db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the user opened/interacted with this notification.",
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image URL for rich notifications.",
                        max_length=500,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link URL for the notification action.",
                        max_length=500,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-scheduled_for"],
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("notification_type", models.CharField(max_length=20)),
                ("total_scheduled", models.IntegerField(default=0)),
                ("total_sent", models.IntegerField(default=0)),
                ("total_failed", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "notification_batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("notification_type", models.CharField(max_length=20)),
                ("title_template", models.CharField(max_length=255)),
                ("body_template", models.TextField()),
                (
                    "available_variables",
                    models.JSONField(
                        default=list,
                        help_text='List of variables that can be used: ["user_name", "dream_title", etc.]',
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates",
            },
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        help_text="Firebase Cloud Messaging registration token for this device.",
                        unique=True,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        help_text="Device platform (android, ios, web).",
                        max_length=10,
                    ),
                ),
                (
                    "device_name",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Human-readable device name (encrypted at rest).",
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        help_text="App version string at time of registration.",
                        max_length=50,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Set to False when token is known invalid or user logs out.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_devices",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscription_info",
                    models.JSONField(
                        help_text="Web Push subscription: {endpoint, keys: {p256dh, auth}}"
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "webpush_subscriptions",
            },
        ),
    ]
