# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="webpushsubscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webpush_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "-scheduled_for"], name="notificatio_user_id_188397_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "scheduled_for"], name="notificatio_status_2554f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_19df93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "is_active"], name="user_device_user_id_14e9e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["platform"], name="user_device_platfor_71adc3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="webpushsubscription",
            index=models.Index(
                fields=["user", "is_active"], name="webpush_sub_user_id_aa7caf_idx"
            ),
        ),
    ]
