# Generated by Django 5.2.6 on 2026-02-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(
                blank=True,
                help_text="Deep link URL for the notification action.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Optional image URL for rich notifications.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="opened_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user opened/interacted with this notification.",
                null=True,
            ),
        ),
    ]
