# Generated by Django 5.2.6 on 2026-02-22 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0003_notification_action_url_notification_image_url_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscription_info",
                    models.JSONField(
                        help_text="Web Push subscription: {endpoint, keys: {p256dh, auth}}"
                    ),
                ),
                ("browser", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webpush_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "webpush_subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="webpush_sub_user_id_aa7caf_idx",
                    )
                ],
            },
        ),
    ]
