# Generated by Django 5.0.6 on 2026-02-24 04:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_webpushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fcm_token', models.TextField(help_text='Firebase Cloud Messaging registration token for this device.', unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], help_text='Device platform (android, ios, web).', max_length=10)),
                ('device_name', models.CharField(blank=True, help_text='Human-readable device name, e.g. "iPhone 15 Pro".', max_length=255)),
                ('app_version', models.CharField(blank=True, help_text='App version string at time of registration.', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Set to False when token is known invalid or user logs out.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_devices',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='user_device_user_id_14e9e9_idx'), models.Index(fields=['platform'], name='user_device_platfor_71adc3_idx')],
            },
        ),
    ]
