# Generated by Django 5.2.6 on 2026-02-24 07:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_userdevice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=encrypted_model_fields.fields.EncryptedTextField(
                help_text="Notification body (encrypted at rest)."
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(
                help_text="Notification title (encrypted at rest)."
            ),
        ),
    ]
