# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_alter_notification_body_alter_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdevice",
            name="device_name",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Human-readable device name (encrypted at rest)."
            ),
        ),
    ]
