# Generated by Django 5.1.15 on 2026-03-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reminder", "Reminder"),
                    ("motivation", "Motivation"),
                    ("progress", "Progress"),
                    ("achievement", "Achievement"),
                    ("check_in", "Check In"),
                    ("rescue", "Rescue"),
                    ("buddy", "Buddy"),
                    ("missed_call", "Missed Call"),
                    ("system", "System"),
                    ("dream_completed", "Dream Completed"),
                    ("weekly_report", "Weekly Report"),
                    ("daily_summary", "Daily Summary"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
