# Generated by Django 5.1.15 on 2026-03-15 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0021_merge_20260310_0205"),
        ("notifications", "0008_alter_notification_notification_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("reminder", "Reminder"),
                    ("motivation", "Motivation"),
                    ("progress", "Progress"),
                    ("achievement", "Achievement"),
                    ("check_in", "Check In"),
                    ("rescue", "Rescue"),
                    ("buddy", "Buddy"),
                    ("missed_call", "Missed Call"),
                    ("system", "System"),
                    ("dream_completed", "Dream Completed"),
                    ("weekly_report", "Weekly Report"),
                    ("daily_summary", "Daily Summary"),
                    ("task_due", "Task Due"),
                    ("task_call", "Task Call"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ReminderPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("custom", "Custom"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="The actual time to send the reminder (user local time)."
                    ),
                ),
                (
                    "days",
                    models.CharField(
                        default="mon,tue,wed,thu,fri,sat,sun",
                        help_text="Comma-separated day abbreviations: mon,tue,wed,thu,fri,sat,sun",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notify_method",
                    models.CharField(
                        choices=[
                            ("push", "Push Notification"),
                            ("task_call", "Task Call (in-app call screen)"),
                            ("both", "Both"),
                        ],
                        default="push",
                        help_text="How to deliver the reminder: push, task_call, or both.",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dream",
                    models.ForeignKey(
                        blank=True,
                        help_text="If null, this is a global preference (applies to all dreams).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_preferences",
                        to="dreams.dream",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminder_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reminder_preferences",
                "ordering": ["time"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="reminder_pr_user_id_286397_idx",
                    ),
                    models.Index(
                        fields=["is_active", "time"],
                        name="reminder_pr_is_acti_f6fef2_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "dream", "time"), name="unique_user_dream_time"
                    )
                ],
            },
        ),
    ]
