# Generated by Django 5.2.6 on 2026-02-08 19:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buddies", "0003_buddypairing_best_encouragement_streak_and_more"),
        ("conversations", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "conversation_type",
                    models.CharField(
                        choices=[
                            ("dream_creation", "Dream Creation"),
                            ("planning", "Planning"),
                            ("check_in", "Check In"),
                            ("adjustment", "Adjustment"),
                            ("general", "General"),
                            ("motivation", "Motivation"),
                            ("rescue", "Rescue"),
                            ("buddy_chat", "Buddy Chat"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "system_prompt",
                    models.TextField(
                        help_text="Custom system prompt for this template."
                    ),
                ),
                (
                    "starter_messages",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of starter message dicts: [{"role": "assistant", "content": "..."}]',
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description shown to users when browsing templates.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Emoji or icon identifier for the template.",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "conversation_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="buddy_pairing",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this is a buddy-to-buddy chat conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="buddies.buddypairing",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="audio_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the uploaded audio file for voice messages.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="URL to an uploaded image for GPT-4 Vision analysis.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="transcription",
            field=models.TextField(
                blank=True, help_text="Whisper transcription of the audio message."
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="conversation_type",
            field=models.CharField(
                choices=[
                    ("dream_creation", "Dream Creation"),
                    ("planning", "Planning"),
                    ("check_in", "Check In"),
                    ("adjustment", "Adjustment"),
                    ("general", "General"),
                    ("motivation", "Motivation"),
                    ("rescue", "Rescue"),
                    ("buddy_chat", "Buddy Chat"),
                ],
                db_index=True,
                default="general",
                max_length=20,
            ),
        ),
    ]
