# Generated by Django 5.0.6 on 2026-02-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_conversationtemplate_conversation_buddy_pairing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Whether this conversation is pinned'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text='Optional conversation title', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='reactions',
            field=models.JSONField(blank=True, default=list, help_text='List of reaction emojis'),
        ),
    ]
