# Generated by Django 5.2.6 on 2026-02-24 07:03

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0006_call"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=encrypted_model_fields.fields.EncryptedTextField(
                help_text="Message content (encrypted at rest)."
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="transcription",
            field=encrypted_model_fields.fields.EncryptedTextField(
                blank=True,
                default="",
                help_text="Whisper transcription of the audio message (encrypted at rest).",
            ),
        ),
    ]
