# Generated by Django 5.2.6 on 2026-02-24 07:26

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0007_alter_message_content_alter_message_transcription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, help_text="Optional conversation title (encrypted at rest)"
            ),
        ),
        migrations.AlterField(
            model_name="conversationsummary",
            name="summary",
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
