# Generated by Django 5.2.11 on 2026-02-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0009_messagereadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereadstatus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
