# Generated by Django 5.2.11 on 2026-02-27 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0010_alter_messagereadstatus_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='messagereadstatus',
            constraint=models.UniqueConstraint(fields=('user', 'conversation'), name='unique_read_status'),
        ),
    ]
