# Generated by Django 5.2.11 on 2026-03-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_alter_messagereadstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration of the audio file in seconds.', null=True),
        ),
    ]
