# Generated by Django 5.2.11 on 2026-03-04 05:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_add_audio_duration_to_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationBranch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional label for this branch.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='conversations.conversation')),
                ('parent_message', models.ForeignKey(help_text='The message from which this branch diverges.', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='conversations.message')),
            ],
            options={
                'db_table': 'conversation_branches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this message belongs to (null = main conversation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='conversations.conversationbranch'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['branch', 'created_at'], name='messages_branch__53fcd0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationbranch',
            index=models.Index(fields=['conversation', '-created_at'], name='conversatio_convers_818bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationbranch',
            index=models.Index(fields=['parent_message'], name='conversatio_parent__d29d47_idx'),
        ),
    ]
