# Generated by Django 5.2.11 on 2026-03-04 11:10

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_conversationbranch_message_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('preference', 'Preference'), ('fact', 'Fact'), ('goal_context', 'Goal Context'), ('style', 'Style')], db_index=True, default='fact', help_text='Memory category (preference, fact, goal_context, style).', max_length=100)),
                ('content', encrypted_model_fields.fields.EncryptedTextField(help_text='The remembered information (encrypted at rest).')),
                ('importance', models.IntegerField(default=3, help_text='Importance level from 1 (low) to 5 (critical).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_conversation', models.ForeignKey(blank=True, help_text='Conversation this memory was extracted from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_memories', to='conversations.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_memories',
                'ordering': ['-importance', '-updated_at'],
                'indexes': [models.Index(fields=['user', '-importance'], name='chat_memori_user_id_cf4dd0_idx'), models.Index(fields=['user', 'key'], name='chat_memori_user_id_695252_idx'), models.Index(fields=['user', 'is_active'], name='chat_memori_user_id_c965fa_idx')],
            },
        ),
    ]
