# Generated by Django 5.1.15 on 2026-03-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0014_add_chatmemory_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The other participant in a friend/buddy chat conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
