# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
import encrypted_model_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buddies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        help_text="Optional conversation title (encrypted at rest)",
                    ),
                ),
                ("total_messages", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chat_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        db_index=True,
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "content",
                    encrypted_model_fields.fields.EncryptedTextField(
                        help_text="Message content (encrypted at rest)."
                    ),
                ),
                (
                    "audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the uploaded audio file for voice messages.",
                        max_length=500,
                    ),
                ),
                (
                    "audio_duration",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of the audio file in seconds.",
                        null=True,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to an uploaded image.",
                        max_length=500,
                    ),
                ),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                (
                    "reactions",
                    models.JSONField(
                        blank=True, default=list, help_text="List of reaction emojis"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageReadStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chat_message_read_statuses",
            },
        ),
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("voice", "Voice"), ("video", "Video")],
                        default="voice",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ringing", "Ringing"),
                            ("accepted", "Accepted"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="ringing",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buddy_pairing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calls",
                        to="buddies.buddypairing",
                    ),
                ),
            ],
            options={
                "db_table": "chat_calls",
                "ordering": ["-created_at"],
            },
        ),
    ]
