# Generated by Django 5.0.14 on 2026-03-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("buddies", "0002_initial"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="callee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incoming_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="call",
            name="caller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outgoing_calls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="buddy_pairing",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this is a buddy-to-buddy chat conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations",
                to="buddies.buddypairing",
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The other participant in a friend/buddy chat conversation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_conversations_as_target",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_conversations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat.chatconversation",
            ),
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_statuses",
                to="chat.chatconversation",
            ),
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="last_read_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chat.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="messagereadstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["caller", "-created_at"], name="chat_calls_caller__7817fd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(
                fields=["callee", "-created_at"], name="chat_calls_callee__34ea1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="call",
            index=models.Index(fields=["status"], name="chat_calls_status_9f9438_idx"),
        ),
        migrations.AddIndex(
            model_name="chatconversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_conver_user_id_9d8b1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_0a903c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(fields=["role"], name="chat_messag_role_ddd811_idx"),
        ),
        migrations.AddConstraint(
            model_name="messagereadstatus",
            constraint=models.UniqueConstraint(
                fields=("user", "conversation"), name="unique_chat_read_status"
            ),
        ),
    ]
